// Format dictionaries frozen from the parity-validated R reference.
#ifndef GLYPARSE_TABLES_H
#define GLYPARSE_TABLES_H
#include <string>
#include <utility>
#include <vector>
namespace gp {
using Pairs = std::vector<std::pair<std::string, std::string>>;
inline const Pairs glycam_table = {{"Hexp", "Hex"},
                                   {"DFucp", "D-Fuc"},
                                   {"DGalp", "Gal"},
                                   {"DGalpA", "GalA"},
                                   {"DGalpN", "GalN"},
                                   {"DGalpNAc", "GalNAc"},
                                   {"DGlcp", "Glc"},
                                   {"DGlcpA", "GlcA"},
                                   {"DGlcpN", "GlcN"},
                                   {"DGlcpNAc", "GlcNAc"},
                                   {"DGulp", "Gul"},
                                   {"DGulpA", "GulA"},
                                   {"DGulpN", "GulN"},
                                   {"DGulpNAc", "GulNAc"},
                                   {"DManp", "Man"},
                                   {"DManpA", "ManA"},
                                   {"DManpN", "ManN"},
                                   {"DManpNAc", "ManNAc"},
                                   {"DAllp", "All"},
                                   {"DAllpA", "AllA"},
                                   {"DAllpN", "AllN"},
                                   {"DAllpNAc", "AllNAc"},
                                   {"DTalp", "Tal"},
                                   {"DTalpA", "TalA"},
                                   {"DTalpN", "TalN"},
                                   {"DTalpNAc", "TalNAc"},
                                   {"LAltp", "Alt"},
                                   {"LAltpA", "AltA"},
                                   {"LAltpN", "AltN"},
                                   {"LAltpNAc", "AltNAc"},
                                   {"LIdop", "Ido"},
                                   {"LIdopA", "IdoA"},
                                   {"LIdopN", "IdoN"},
                                   {"LIdopNAc", "IdoNAc"},
                                   {"DQuip", "Qui"},
                                   {"DQuipNAc", "QuiNAc"},
                                   {"D6dGulp", "6dGul"},
                                   {"D6dTalp", "6dTal"},
                                   {"L6dAltp", "6dAlt"},
                                   {"L6dAltpNAc", "6dAltNAc"},
                                   {"D6dTalpNAc", "6dTalNAc"},
                                   {"LFucp", "Fuc"},
                                   {"LFucpNAc", "FucNAc"},
                                   {"LRhap", "Rha"},
                                   {"LRhapNAc", "RhaNAc"},
                                   {"DOlip", "Oli"},
                                   {"DTyvp", "Tyv"},
                                   {"DAbep", "Abe"},
                                   {"DParp", "Par"},
                                   {"DDigp", "Dig"},
                                   {"LColp", "Col"},
                                   {"LArap", "Ara"},
                                   {"LLyxp", "L-Lyx"},
                                   {"DRibp", "Rib"},
                                   {"DXylf", "Xylf"},
                                   {"DXylp", "Xyl"},
                                   {"DNeup5Ac", "Neu5Ac"},
                                   {"DNeup5Gc", "Neu5Gc"},
                                   {"Neup", "Neu"},
                                   {"Neup5Ac", "Neu5Ac"},
                                   {"Neup5Gc", "Neu5Gc"},
                                   {"DKDNp", "Kdn"},
                                   {"Kdnp", "Kdn"},
                                   {"Psep", "Pse"},
                                   {"Legp", "Leg"},
                                   {"Acip", "Aci"},
                                   {"4eLegp", "4eLeg"},
                                   {"DBacp", "Bac"},
                                   {"LDmanHepp", "LDmanHep"},
                                   {"DKdop", "Kdo"},
                                   {"DDhap", "Dha"},
                                   {"DDmanHepp", "DDmanHep"},
                                   {"DMurp", "Mur"},
                                   {"DMurpNAc", "MurNAc"},
                                   {"DMurpNGc", "MurNGc"},
                                   {"DApif", "D-Apif"},
                                   {"DApip", "D-Api"},
                                   {"DFrup", "Fru"},
                                   {"DTagp", "Tag"},
                                   {"LSorp", "Sor"},
                                   {"DPsip", "Psi"},
                                   {"LGalp", "L-Gal"},
                                   {"LGalpA", "L-GalA"},
                                   {"LGalpN", "L-GalN"},
                                   {"LGalpNAc", "L-GalNAc"},
                                   {"LGlcp", "L-Glc"},
                                   {"LGlcpA", "L-GlcA"},
                                   {"LGlcpN", "L-GlcN"},
                                   {"LGlcpNAc", "L-GlcNAc"},
                                   {"LGulp", "L-Gul"},
                                   {"LGulpA", "L-GulA"},
                                   {"LGulpN", "L-GulN"},
                                   {"LGulpNAc", "L-GulNAc"},
                                   {"LManp", "L-Man"},
                                   {"LManpA", "L-ManA"},
                                   {"LManpN", "L-ManN"},
                                   {"LManpNAc", "L-ManNAc"},
                                   {"LAllp", "L-All"},
                                   {"LAllpA", "L-AllA"},
                                   {"LAllpN", "L-AllN"},
                                   {"LAllpNAc", "L-AllNAc"},
                                   {"LTalp", "L-Tal"},
                                   {"LTalpA", "L-TalA"},
                                   {"LTalpN", "L-TalN"},
                                   {"LTalpNAc", "L-TalNAc"},
                                   {"DAltp", "D-Alt"},
                                   {"DAltpA", "D-AltA"},
                                   {"DAltpN", "D-AltN"},
                                   {"DAltpNAc", "D-AltNAc"},
                                   {"DIdop", "D-Ido"},
                                   {"DIdopA", "D-IdoA"},
                                   {"DIdopN", "D-IdoN"},
                                   {"DIdopNAc", "D-IdoNAc"},
                                   {"LQuip", "L-Qui"},
                                   {"LQuipNAc", "L-QuiNAc"},
                                   {"L6dGulp", "L-6dGul"},
                                   {"L6dTalp", "L-6dTal"},
                                   {"D6dAltp", "D-6dAlt"},
                                   {"D6dAltpNAc", "D-6dAltNAc"},
                                   {"L6dTalpNAc", "L-6dTalNAc"},
                                   {"DFucpNAc", "D-FucNAc"},
                                   {"DRhap", "D-Rha"},
                                   {"DRhapNAc", "D-RhaNAc"},
                                   {"LOlip", "L-Oli"},
                                   {"LTyvp", "L-Tyv"},
                                   {"LAbep", "L-Abe"},
                                   {"LParp", "L-Par"},
                                   {"LDigp", "L-Dig"},
                                   {"DColp", "D-Col"},
                                   {"DArap", "D-Ara"},
                                   {"DLyxp", "Lyx"},
                                   {"LRibp", "L-Rib"},
                                   {"LXylf", "L-Xylf"},
                                   {"LXylp", "L-Xyl"},
                                   {"LNeup5Ac", "L-Neu5Ac"},
                                   {"LNeup5Gc", "L-Neu5Gc"},
                                   {"LKDNp", "L-Kdn"},
                                   {"LBacp", "L-Bac"},
                                   {"LKdop", "L-Kdo"},
                                   {"LDhap", "L-Dha"},
                                   {"LMurp", "L-Mur"},
                                   {"LMurpNAc", "L-MurNAc"},
                                   {"LMurpNGc", "L-MurNGc"},
                                   {"LApif", "Apif"},
                                   {"LApip", "Api"},
                                   {"LFrup", "L-Fru"},
                                   {"LTagp", "L-Tag"},
                                   {"DSorp", "D-Sor"},
                                   {"LPsip", "L-Psi"},
                                   {"DFucf", "D-Fucf"},
                                   {"DGalf", "Galf"},
                                   {"DGalfA", "GalfA"},
                                   {"DGalfN", "GalfN"},
                                   {"DGalfNAc", "GalfNAc"},
                                   {"DGlcf", "Glcf"},
                                   {"DGlcfA", "GlcfA"},
                                   {"DGlcfN", "GlcfN"},
                                   {"DGlcfNAc", "GlcfNAc"},
                                   {"DGulf", "Gulf"},
                                   {"DGulfA", "GulfA"},
                                   {"DGulfN", "GulfN"},
                                   {"DGulfNAc", "GulfNAc"},
                                   {"DManf", "Manf"},
                                   {"DManfA", "ManfA"},
                                   {"DManfN", "ManfN"},
                                   {"DManfNAc", "ManfNAc"},
                                   {"DAllf", "Allf"},
                                   {"DAllfA", "AllfA"},
                                   {"DAllfN", "AllfN"},
                                   {"DAllfNAc", "AllfNAc"},
                                   {"DTalf", "Talf"},
                                   {"DTalfA", "TalfA"},
                                   {"DTalfN", "TalfN"},
                                   {"DTalfNAc", "TalfNAc"},
                                   {"LAltf", "Altf"},
                                   {"LAltfA", "AltfA"},
                                   {"LAltfN", "AltfN"},
                                   {"LAltfNAc", "AltfNAc"},
                                   {"LIdof", "Idof"},
                                   {"LIdofA", "IdofA"},
                                   {"LIdofN", "IdofN"},
                                   {"LIdofNAc", "IdofNAc"},
                                   {"DQuif", "Quif"},
                                   {"DQuifNAc", "QuifNAc"},
                                   {"D6dGulf", "6dGulf"},
                                   {"D6dTalf", "6dTalf"},
                                   {"L6dAltf", "6dAltf"},
                                   {"L6dAltfNAc", "6dAltfNAc"},
                                   {"D6dTalfNAc", "6dTalfNAc"},
                                   {"LFucf", "Fucf"},
                                   {"LFucfNAc", "FucfNAc"},
                                   {"LRhaf", "Rhaf"},
                                   {"LRhafNAc", "RhafNAc"},
                                   {"DOlif", "Olif"},
                                   {"DTyvf", "Tyvf"},
                                   {"DAbef", "Abef"},
                                   {"DParf", "Parf"},
                                   {"DDigf", "Digf"},
                                   {"LColf", "Colf"},
                                   {"LAraf", "Araf"},
                                   {"LLyxf", "L-Lyxf"},
                                   {"DRibf", "Ribf"},
                                   {"DNeuf5Ac", "Neuf5Ac"},
                                   {"DNeuf5Gc", "Neuf5Gc"},
                                   {"Neuf", "Neuf"},
                                   {"Neuf5Ac", "Neuf5Ac"},
                                   {"Neuf5Gc", "Neuf5Gc"},
                                   {"DKDNf", "Kdnf"},
                                   {"Kdnf", "Kdnf"},
                                   {"Psef", "Psef"},
                                   {"Legf", "Legf"},
                                   {"Acif", "Acif"},
                                   {"4eLegf", "4eLegf"},
                                   {"DBacf", "Bacf"},
                                   {"LDmanHepf", "LDmanHepf"},
                                   {"DKdof", "Kdof"},
                                   {"DDhaf", "Dhaf"},
                                   {"DDmanHepf", "DDmanHepf"},
                                   {"DMurf", "Murf"},
                                   {"DMurfNAc", "MurfNAc"},
                                   {"DMurfNGc", "MurfNGc"},
                                   {"DFruf", "Fruf"},
                                   {"DTagf", "Tagf"},
                                   {"LSorf", "Sorf"},
                                   {"DPsif", "Psif"},
                                   {"LGalf", "L-Galf"},
                                   {"LGalfA", "L-GalfA"},
                                   {"LGalfN", "L-GalfN"},
                                   {"LGalfNAc", "L-GalfNAc"},
                                   {"LGlcf", "L-Glcf"},
                                   {"LGlcfA", "L-GlcfA"},
                                   {"LGlcfN", "L-GlcfN"},
                                   {"LGlcfNAc", "L-GlcfNAc"},
                                   {"LGulf", "L-Gulf"},
                                   {"LGulfA", "L-GulfA"},
                                   {"LGulfN", "L-GulfN"},
                                   {"LGulfNAc", "L-GulfNAc"},
                                   {"LManf", "L-Manf"},
                                   {"LManfA", "L-ManfA"},
                                   {"LManfN", "L-ManfN"},
                                   {"LManfNAc", "L-ManfNAc"},
                                   {"LAllf", "L-Allf"},
                                   {"LAllfA", "L-AllfA"},
                                   {"LAllfN", "L-AllfN"},
                                   {"LAllfNAc", "L-AllfNAc"},
                                   {"LTalf", "L-Talf"},
                                   {"LTalfA", "L-TalfA"},
                                   {"LTalfN", "L-TalfN"},
                                   {"LTalfNAc", "L-TalfNAc"},
                                   {"DAltf", "D-Altf"},
                                   {"DAltfA", "D-AltfA"},
                                   {"DAltfN", "D-AltfN"},
                                   {"DAltfNAc", "D-AltfNAc"},
                                   {"DIdof", "D-Idof"},
                                   {"DIdofA", "D-IdofA"},
                                   {"DIdofN", "D-IdofN"},
                                   {"DIdofNAc", "D-IdofNAc"},
                                   {"LQuif", "L-Quif"},
                                   {"LQuifNAc", "L-QuifNAc"},
                                   {"L6dGulf", "L-6dGulf"},
                                   {"L6dTalf", "L-6dTalf"},
                                   {"D6dAltf", "D-6dAltf"},
                                   {"D6dAltfNAc", "D-6dAltfNAc"},
                                   {"L6dTalfNAc", "L-6dTalfNAc"},
                                   {"DFucfNAc", "D-FucfNAc"},
                                   {"DRhaf", "D-Rhaf"},
                                   {"DRhafNAc", "D-RhafNAc"},
                                   {"LOlif", "L-Olif"},
                                   {"LTyvf", "L-Tyvf"},
                                   {"LAbef", "L-Abef"},
                                   {"LParf", "L-Parf"},
                                   {"LDigf", "L-Digf"},
                                   {"DColf", "D-Colf"},
                                   {"DAraf", "D-Araf"},
                                   {"DLyxf", "Lyxf"},
                                   {"LRibf", "L-Ribf"},
                                   {"LNeuf5Ac", "L-Neuf5Ac"},
                                   {"LNeuf5Gc", "L-Neuf5Gc"},
                                   {"LKDNf", "L-Kdnf"},
                                   {"LBacf", "L-Bacf"},
                                   {"LKdof", "L-Kdof"},
                                   {"LDhaf", "L-Dhaf"},
                                   {"LMurf", "L-Murf"},
                                   {"LMurfNAc", "L-MurfNAc"},
                                   {"LMurfNGc", "L-MurfNGc"},
                                   {"LFruf", "L-Fruf"},
                                   {"LTagf", "L-Tagf"},
                                   {"DSorf", "D-Sorf"},
                                   {"LPsif", "L-Psif"}};
inline const Pairs linucs_table = {{"6-deoxy-HexpNAc", "dHexNAc"},
                                   {"6-deoxy-HexNAc", "dHexNAc"},
                                   {"HexpNAc", "HexNAc"},
                                   {"HexNAc", "HexNAc"},
                                   {"HexpN", "HexN"},
                                   {"HexN", "HexN"},
                                   {"HexpA", "HexA"},
                                   {"HexA", "HexA"},
                                   {"6-deoxy-Hexp", "dHex"},
                                   {"6-deoxy-Hexf", "dHex"},
                                   {"6-deoxy-Hex", "dHex"},
                                   {"6-deoxy-L-AltpNAc", "6dAltNAc"},
                                   {"6-deoxy-D-TalpNAc", "6dTalNAc"},
                                   {"6-deoxy-L-Altp", "6dAlt"},
                                   {"6-deoxy-D-Gulp", "6dGul"},
                                   {"6-deoxy-D-Talp", "6dTal"},
                                   {"Hexp", "Hex"},
                                   {"Hexf", "Hex"},
                                   {"Hex", "Hex"},
                                   {"Penp", "Pen"},
                                   {"Penf", "Pen"},
                                   {"Pen", "Pen"},
                                   {"D-GlcpNAc", "GlcNAc"},
                                   {"D-ManpNAc", "ManNAc"},
                                   {"D-GalpNAc", "GalNAc"},
                                   {"D-GulpNAc", "GulNAc"},
                                   {"L-AltpNAc", "AltNAc"},
                                   {"D-AllpNAc", "AllNAc"},
                                   {"D-TalpNAc", "TalNAc"},
                                   {"L-IdopNAc", "IdoNAc"},
                                   {"D-GlcpN", "GlcN"},
                                   {"D-ManpN", "ManN"},
                                   {"D-GalpN", "GalN"},
                                   {"D-GulpN", "GulN"},
                                   {"L-AltpN", "AltN"},
                                   {"D-AllpN", "AllN"},
                                   {"D-TalpN", "TalN"},
                                   {"L-IdopN", "IdoN"},
                                   {"D-GlcpA", "GlcA"},
                                   {"D-ManpA", "ManA"},
                                   {"D-GalpA", "GalA"},
                                   {"D-GulpA", "GulA"},
                                   {"L-AltpA", "AltA"},
                                   {"D-AllpA", "AllA"},
                                   {"D-TalpA", "TalA"},
                                   {"L-IdopA", "IdoA"},
                                   {"D-Glcp", "Glc"},
                                   {"D-Glc", "Glc"},
                                   {"D-Manp", "Man"},
                                   {"D-Galp", "Gal"},
                                   {"D-Gulp", "Gul"},
                                   {"L-Altp", "Alt"},
                                   {"D-Allp", "All"},
                                   {"D-Talp", "Tal"},
                                   {"L-Idop", "Ido"},
                                   {"L-FucpNAc", "FucNAc"},
                                   {"D-QuipNAc", "QuiNAc"},
                                   {"L-RhapNAc", "RhaNAc"},
                                   {"L-Fucp", "Fuc"},
                                   {"D-Fucp", "D-Fuc"},
                                   {"D-Quip", "Qui"},
                                   {"L-Rhap", "Rha"},
                                   {"D-Olip", "Oli"},
                                   {"D-Tyvp", "Tyv"},
                                   {"D-Abep", "Abe"},
                                   {"D-Parp", "Par"},
                                   {"D-Digp", "Dig"},
                                   {"L-Colp", "Col"},
                                   {"L-Arap", "Ara"},
                                   {"L-Araf", "Araf"},
                                   {"L-Lyxp", "L-Lyx"},
                                   {"L-Lyxf", "L-Lyxf"},
                                   {"D-Xylp", "Xyl"},
                                   {"D-Xylf", "Xylf"},
                                   {"D-Ribp", "Rib"},
                                   {"D-Ribf", "Ribf"},
                                   {"Neup5Ac", "Neu5Ac"},
                                   {"NeupAc", "Neu5Ac"},
                                   {"Neup5Gc", "Neu5Gc"},
                                   {"NeupGc", "Neu5Gc"},
                                   {"Neup", "Neu"},
                                   {"Kdnp", "Kdn"},
                                   {"D-Kdop", "Kdo"},
                                   {"D-Dhap", "Dha"},
                                   {"Psep", "Pse"},
                                   {"Legp", "Leg"},
                                   {"Acip", "Aci"},
                                   {"4eLegp", "4eLeg"},
                                   {"Bacp", "Bac"},
                                   {"D-Bacp", "Bac"},
                                   {"LDmanHepp", "LDmanHep"},
                                   {"DDmanHepp", "DDmanHep"},
                                   {"MurpNAc", "MurNAc"},
                                   {"MurpNGc", "MurNGc"},
                                   {"Murp", "Mur"},
                                   {"D-Apif", "D-Apif"},
                                   {"D-Apip", "D-Api"},
                                   {"D-Frup", "Fru"},
                                   {"D-Tagp", "Tag"},
                                   {"L-Sorp", "Sor"},
                                   {"D-Psip", "Psi"},
                                   {"6-deoxy-D-AltpNAc", "D-6dAltNAc"},
                                   {"6-deoxy-L-TalpNAc", "L-6dTalNAc"},
                                   {"6-deoxy-D-Altp", "D-6dAlt"},
                                   {"6-deoxy-L-Gulp", "L-6dGul"},
                                   {"6-deoxy-L-Talp", "L-6dTal"},
                                   {"L-GlcpNAc", "L-GlcNAc"},
                                   {"L-ManpNAc", "L-ManNAc"},
                                   {"L-GalpNAc", "L-GalNAc"},
                                   {"L-GulpNAc", "L-GulNAc"},
                                   {"D-AltpNAc", "D-AltNAc"},
                                   {"L-AllpNAc", "L-AllNAc"},
                                   {"L-TalpNAc", "L-TalNAc"},
                                   {"D-IdopNAc", "D-IdoNAc"},
                                   {"L-GlcpN", "L-GlcN"},
                                   {"L-ManpN", "L-ManN"},
                                   {"L-GalpN", "L-GalN"},
                                   {"L-GulpN", "L-GulN"},
                                   {"D-AltpN", "D-AltN"},
                                   {"L-AllpN", "L-AllN"},
                                   {"L-TalpN", "L-TalN"},
                                   {"D-IdopN", "D-IdoN"},
                                   {"L-GlcpA", "L-GlcA"},
                                   {"L-ManpA", "L-ManA"},
                                   {"L-GalpA", "L-GalA"},
                                   {"L-GulpA", "L-GulA"},
                                   {"D-AltpA", "D-AltA"},
                                   {"L-AllpA", "L-AllA"},
                                   {"L-TalpA", "L-TalA"},
                                   {"D-IdopA", "D-IdoA"},
                                   {"L-Glcp", "L-Glc"},
                                   {"L-Glc", "L-Glc"},
                                   {"L-Manp", "L-Man"},
                                   {"L-Galp", "L-Gal"},
                                   {"L-Gulp", "L-Gul"},
                                   {"D-Altp", "D-Alt"},
                                   {"L-Allp", "L-All"},
                                   {"L-Talp", "L-Tal"},
                                   {"D-Idop", "D-Ido"},
                                   {"D-FucpNAc", "D-FucNAc"},
                                   {"L-QuipNAc", "L-QuiNAc"},
                                   {"D-RhapNAc", "D-RhaNAc"},
                                   {"L-Quip", "L-Qui"},
                                   {"D-Rhap", "D-Rha"},
                                   {"L-Olip", "L-Oli"},
                                   {"L-Tyvp", "L-Tyv"},
                                   {"L-Abep", "L-Abe"},
                                   {"L-Parp", "L-Par"},
                                   {"L-Digp", "L-Dig"},
                                   {"D-Colp", "D-Col"},
                                   {"D-Arap", "D-Ara"},
                                   {"D-Araf", "D-Araf"},
                                   {"D-Lyxp", "Lyx"},
                                   {"D-Lyxf", "Lyxf"},
                                   {"L-Xylp", "L-Xyl"},
                                   {"L-Xylf", "L-Xylf"},
                                   {"L-Ribp", "L-Rib"},
                                   {"L-Ribf", "L-Ribf"},
                                   {"L-Kdop", "L-Kdo"},
                                   {"L-Dhap", "L-Dha"},
                                   {"L-Bacp", "L-Bac"},
                                   {"L-Apif", "Apif"},
                                   {"L-Apip", "Api"},
                                   {"L-Frup", "L-Fru"},
                                   {"L-Tagp", "L-Tag"},
                                   {"D-Sorp", "D-Sor"},
                                   {"L-Psip", "L-Psi"},
                                   {"6-deoxy-L-AltfNAc", "6dAltfNAc"},
                                   {"6-deoxy-D-TalfNAc", "6dTalfNAc"},
                                   {"6-deoxy-L-Altf", "6dAltf"},
                                   {"6-deoxy-D-Gulf", "6dGulf"},
                                   {"6-deoxy-D-Talf", "6dTalf"},
                                   {"D-GlcfNAc", "GlcfNAc"},
                                   {"D-ManfNAc", "ManfNAc"},
                                   {"D-GalfNAc", "GalfNAc"},
                                   {"D-GulfNAc", "GulfNAc"},
                                   {"L-AltfNAc", "AltfNAc"},
                                   {"D-AllfNAc", "AllfNAc"},
                                   {"D-TalfNAc", "TalfNAc"},
                                   {"L-IdofNAc", "IdofNAc"},
                                   {"D-GlcfN", "GlcfN"},
                                   {"D-ManfN", "ManfN"},
                                   {"D-GalfN", "GalfN"},
                                   {"D-GulfN", "GulfN"},
                                   {"L-AltfN", "AltfN"},
                                   {"D-AllfN", "AllfN"},
                                   {"D-TalfN", "TalfN"},
                                   {"L-IdofN", "IdofN"},
                                   {"D-GlcfA", "GlcfA"},
                                   {"D-ManfA", "ManfA"},
                                   {"D-GalfA", "GalfA"},
                                   {"D-GulfA", "GulfA"},
                                   {"L-AltfA", "AltfA"},
                                   {"D-AllfA", "AllfA"},
                                   {"D-TalfA", "TalfA"},
                                   {"L-IdofA", "IdofA"},
                                   {"D-Glcf", "Glcf"},
                                   {"D-Manf", "Manf"},
                                   {"D-Galf", "Galf"},
                                   {"D-Gulf", "Gulf"},
                                   {"L-Altf", "Altf"},
                                   {"D-Allf", "Allf"},
                                   {"D-Talf", "Talf"},
                                   {"L-Idof", "Idof"},
                                   {"L-FucfNAc", "FucfNAc"},
                                   {"D-QuifNAc", "QuifNAc"},
                                   {"L-RhafNAc", "RhafNAc"},
                                   {"L-Fucf", "Fucf"},
                                   {"D-Fucf", "D-Fucf"},
                                   {"D-Quif", "Quif"},
                                   {"L-Rhaf", "Rhaf"},
                                   {"D-Olif", "Olif"},
                                   {"D-Tyvf", "Tyvf"},
                                   {"D-Abef", "Abef"},
                                   {"D-Parf", "Parf"},
                                   {"D-Digf", "Digf"},
                                   {"L-Colf", "Colf"},
                                   {"Neuf5Ac", "Neuf5Ac"},
                                   {"NeufAc", "Neuf5Ac"},
                                   {"Neuf5Gc", "Neuf5Gc"},
                                   {"NeufGc", "Neuf5Gc"},
                                   {"Neuf", "Neuf"},
                                   {"Kdnf", "Kdnf"},
                                   {"D-Kdof", "Kdof"},
                                   {"D-Dhaf", "Dhaf"},
                                   {"Psef", "Psef"},
                                   {"Legf", "Legf"},
                                   {"Acif", "Acif"},
                                   {"4eLegf", "4eLegf"},
                                   {"Bacf", "Bacf"},
                                   {"D-Bacf", "Bacf"},
                                   {"LDmanHepf", "LDmanHepf"},
                                   {"DDmanHepf", "DDmanHepf"},
                                   {"MurfNAc", "MurfNAc"},
                                   {"MurfNGc", "MurfNGc"},
                                   {"Murf", "Murf"},
                                   {"D-Fruf", "Fruf"},
                                   {"D-Tagf", "Tagf"},
                                   {"L-Sorf", "Sorf"},
                                   {"D-Psif", "Psif"},
                                   {"6-deoxy-D-AltfNAc", "D-6dAltfNAc"},
                                   {"6-deoxy-L-TalfNAc", "L-6dTalfNAc"},
                                   {"6-deoxy-D-Altf", "D-6dAltf"},
                                   {"6-deoxy-L-Gulf", "L-6dGulf"},
                                   {"6-deoxy-L-Talf", "L-6dTalf"},
                                   {"L-GlcfNAc", "L-GlcfNAc"},
                                   {"L-ManfNAc", "L-ManfNAc"},
                                   {"L-GalfNAc", "L-GalfNAc"},
                                   {"L-GulfNAc", "L-GulfNAc"},
                                   {"D-AltfNAc", "D-AltfNAc"},
                                   {"L-AllfNAc", "L-AllfNAc"},
                                   {"L-TalfNAc", "L-TalfNAc"},
                                   {"D-IdofNAc", "D-IdofNAc"},
                                   {"L-GlcfN", "L-GlcfN"},
                                   {"L-ManfN", "L-ManfN"},
                                   {"L-GalfN", "L-GalfN"},
                                   {"L-GulfN", "L-GulfN"},
                                   {"D-AltfN", "D-AltfN"},
                                   {"L-AllfN", "L-AllfN"},
                                   {"L-TalfN", "L-TalfN"},
                                   {"D-IdofN", "D-IdofN"},
                                   {"L-GlcfA", "L-GlcfA"},
                                   {"L-ManfA", "L-ManfA"},
                                   {"L-GalfA", "L-GalfA"},
                                   {"L-GulfA", "L-GulfA"},
                                   {"D-AltfA", "D-AltfA"},
                                   {"L-AllfA", "L-AllfA"},
                                   {"L-TalfA", "L-TalfA"},
                                   {"D-IdofA", "D-IdofA"},
                                   {"L-Glcf", "L-Glcf"},
                                   {"L-Manf", "L-Manf"},
                                   {"L-Galf", "L-Galf"},
                                   {"L-Gulf", "L-Gulf"},
                                   {"D-Altf", "D-Altf"},
                                   {"L-Allf", "L-Allf"},
                                   {"L-Talf", "L-Talf"},
                                   {"D-Idof", "D-Idof"},
                                   {"D-FucfNAc", "D-FucfNAc"},
                                   {"L-QuifNAc", "L-QuifNAc"},
                                   {"D-RhafNAc", "D-RhafNAc"},
                                   {"L-Quif", "L-Quif"},
                                   {"D-Rhaf", "D-Rhaf"},
                                   {"L-Olif", "L-Olif"},
                                   {"L-Tyvf", "L-Tyvf"},
                                   {"L-Abef", "L-Abef"},
                                   {"L-Parf", "L-Parf"},
                                   {"L-Digf", "L-Digf"},
                                   {"D-Colf", "D-Colf"},
                                   {"L-Kdof", "L-Kdof"},
                                   {"L-Dhaf", "L-Dhaf"},
                                   {"L-Bacf", "L-Bacf"},
                                   {"L-Fruf", "L-Fruf"},
                                   {"L-Tagf", "L-Tagf"},
                                   {"D-Sorf", "D-Sorf"},
                                   {"L-Psif", "L-Psif"}};
inline const Pairs extended_table = {{"Hexp", "Hex"},
                                     {"HexpNAc", "HexNAc"},
                                     {"HexpN", "HexN"},
                                     {"HexpA", "HexA"},
                                     {"dHexp", "dHex"},
                                     {"dHexpNAc", "dHexNAc"},
                                     {"ddHexp", "ddHex"},
                                     {"Penp", "Pen"},
                                     {"NeuAcp", "NeuAc"},
                                     {"NeuGcp", "NeuGc"},
                                     {"gNeup", "gNeu"},
                                     {"gKdnp", "gKdn"},
                                     {"gPsep", "gPse"},
                                     {"gLegp", "gLeg"},
                                     {"gAcip", "gAci"},
                                     {"g4eLegp", "g4eLeg"},
                                     {"gBacp", "gBac"},
                                     {"Hepp", "Hep"},
                                     {"gKdop", "gKdo"},
                                     {"HeppA", "HepA"},
                                     {"MurAcp", "MurAc"},
                                     {"MurGcp", "MurGc"},
                                     {"gMurp", "gMur"},
                                     {"Glcp", "Glc"},
                                     {"Manp", "Man"},
                                     {"Galp", "Gal"},
                                     {"Gulp", "Gul"},
                                     {"Altp", "Alt"},
                                     {"Allp", "All"},
                                     {"Talp", "Tal"},
                                     {"Idop", "Ido"},
                                     {"GlcpNAc", "GlcNAc"},
                                     {"GalpNAc", "GalNAc"},
                                     {"ManpNAc", "ManNAc"},
                                     {"GulpNAc", "GulNAc"},
                                     {"AltpNAc", "AltNAc"},
                                     {"AllpNAc", "AllNAc"},
                                     {"TalpNAc", "TalNAc"},
                                     {"IdopNAc", "IdoNAc"},
                                     {"GlcpN", "GlcN"},
                                     {"ManpN", "ManN"},
                                     {"GalpN", "GalN"},
                                     {"GulpN", "GulN"},
                                     {"AltpN", "AltN"},
                                     {"AllpN", "AllN"},
                                     {"TalpN", "TalN"},
                                     {"IdopN", "IdoN"},
                                     {"GlcpA", "GlcA"},
                                     {"ManpA", "ManA"},
                                     {"GalpA", "GalA"},
                                     {"GulpA", "GulA"},
                                     {"AltpA", "AltA"},
                                     {"AllpA", "AllA"},
                                     {"TalpA", "TalA"},
                                     {"IdopA", "IdoA"},
                                     {"Fucp", "Fuc"},
                                     {"Quip", "Qui"},
                                     {"Rhap", "Rha"},
                                     {"6dGulp", "6dGul"},
                                     {"6dAltp", "6dAlt"},
                                     {"6dTalp", "6dTal"},
                                     {"QuipNAc", "QuiNAc"},
                                     {"RhapNAc", "RhaNAc"},
                                     {"6dAltpNAc", "6dAltNAc"},
                                     {"6dTalpNAc", "6dTalNAc"},
                                     {"FucpNAc", "FucNAc"},
                                     {"Olip", "Oli"},
                                     {"Tyvp", "Tyv"},
                                     {"Abep", "Abe"},
                                     {"Parp", "Par"},
                                     {"Digp", "Dig"},
                                     {"Colp", "Col"},
                                     {"Arap", "Ara"},
                                     {"Lyxp", "Lyx"},
                                     {"Xylp", "Xyl"},
                                     {"Ribp", "Rib"},
                                     {"Neup5Ac", "Neu5Ac"},
                                     {"Neup5Gc", "Neu5Gc"},
                                     {"Neup", "Neu"},
                                     {"Kdnp", "Kdn"},
                                     {"Psep", "Pse"},
                                     {"Legp", "Leg"},
                                     {"Acip", "Aci"},
                                     {"4eLegp", "4eLeg"},
                                     {"Bacp", "Bac"},
                                     {"LDmanHep", "LDmanHep"},
                                     {"Kdop", "Kdo"},
                                     {"Dhap", "Dha"},
                                     {"DDmanHep", "DDmanHep"},
                                     {"MurpNAc", "MurNAc"},
                                     {"MurpN2Gc", "MurNGc"},
                                     {"Murp", "Mur"},
                                     {"Eryp3CMeOH", "Api"},
                                     {"Frup", "Fru"},
                                     {"Tagp", "Tag"},
                                     {"Sorp", "Sor"},
                                     {"Psip", "Psi"},
                                     {"Glcf", "Glcf"},
                                     {"Manf", "Manf"},
                                     {"Galf", "Galf"},
                                     {"Gulf", "Gulf"},
                                     {"Altf", "Altf"},
                                     {"Allf", "Allf"},
                                     {"Talf", "Talf"},
                                     {"Idof", "Idof"},
                                     {"GlcfNAc", "GlcfNAc"},
                                     {"GalfNAc", "GalfNAc"},
                                     {"ManfNAc", "ManfNAc"},
                                     {"GulfNAc", "GulfNAc"},
                                     {"AltfNAc", "AltfNAc"},
                                     {"AllfNAc", "AllfNAc"},
                                     {"TalfNAc", "TalfNAc"},
                                     {"IdofNAc", "IdofNAc"},
                                     {"GlcfN", "GlcfN"},
                                     {"ManfN", "ManfN"},
                                     {"GalfN", "GalfN"},
                                     {"GulfN", "GulfN"},
                                     {"AltfN", "AltfN"},
                                     {"AllfN", "AllfN"},
                                     {"TalfN", "TalfN"},
                                     {"IdofN", "IdofN"},
                                     {"GlcfA", "GlcfA"},
                                     {"ManfA", "ManfA"},
                                     {"GalfA", "GalfA"},
                                     {"GulfA", "GulfA"},
                                     {"AltfA", "AltfA"},
                                     {"AllfA", "AllfA"},
                                     {"TalfA", "TalfA"},
                                     {"IdofA", "IdofA"},
                                     {"Fucf", "Fucf"},
                                     {"Quif", "Quif"},
                                     {"Rhaf", "Rhaf"},
                                     {"6dGulf", "6dGulf"},
                                     {"6dAltf", "6dAltf"},
                                     {"6dTalf", "6dTalf"},
                                     {"QuifNAc", "QuifNAc"},
                                     {"RhafNAc", "RhafNAc"},
                                     {"6dAltfNAc", "6dAltfNAc"},
                                     {"6dTalfNAc", "6dTalfNAc"},
                                     {"FucfNAc", "FucfNAc"},
                                     {"Olif", "Olif"},
                                     {"Tyvf", "Tyvf"},
                                     {"Abef", "Abef"},
                                     {"Parf", "Parf"},
                                     {"Digf", "Digf"},
                                     {"Colf", "Colf"},
                                     {"Araf", "Araf"},
                                     {"Lyxf", "Lyxf"},
                                     {"Xylf", "Xylf"},
                                     {"Ribf", "Ribf"},
                                     {"Neuf5Ac", "Neuf5Ac"},
                                     {"Neuf5Gc", "Neuf5Gc"},
                                     {"Neuf", "Neuf"},
                                     {"Kdnf", "Kdnf"},
                                     {"Psef", "Psef"},
                                     {"Legf", "Legf"},
                                     {"Acif", "Acif"},
                                     {"4eLegf", "4eLegf"},
                                     {"Bacf", "Bacf"},
                                     {"LDmanHepf", "LDmanHepf"},
                                     {"Kdof", "Kdof"},
                                     {"Dhaf", "Dhaf"},
                                     {"DDmanHepf", "DDmanHepf"},
                                     {"MurfNAc", "MurfNAc"},
                                     {"MurfNGc", "MurfNGc"},
                                     {"Murf", "Murf"},
                                     {"Apif", "Apif"},
                                     {"Fruf", "Fruf"},
                                     {"Tagf", "Tagf"},
                                     {"Sorf", "Sorf"},
                                     {"Psif", "Psif"},
                                     {"L-Glcp", "L-Glc"},
                                     {"L-Manp", "L-Man"},
                                     {"L-Galp", "L-Gal"},
                                     {"L-Gulp", "L-Gul"},
                                     {"D-Altp", "D-Alt"},
                                     {"L-Allp", "L-All"},
                                     {"L-Talp", "L-Tal"},
                                     {"D-Idop", "D-Ido"},
                                     {"L-GlcpNAc", "L-GlcNAc"},
                                     {"L-GalpNAc", "L-GalNAc"},
                                     {"L-ManpNAc", "L-ManNAc"},
                                     {"L-GulpNAc", "L-GulNAc"},
                                     {"D-AltpNAc", "D-AltNAc"},
                                     {"L-AllpNAc", "L-AllNAc"},
                                     {"L-TalpNAc", "L-TalNAc"},
                                     {"D-IdopNAc", "D-IdoNAc"},
                                     {"L-GlcpN", "L-GlcN"},
                                     {"L-ManpN", "L-ManN"},
                                     {"L-GalpN", "L-GalN"},
                                     {"L-GulpN", "L-GulN"},
                                     {"D-AltpN", "D-AltN"},
                                     {"L-AllpN", "L-AllN"},
                                     {"L-TalpN", "L-TalN"},
                                     {"D-IdopN", "D-IdoN"},
                                     {"L-GlcpA", "L-GlcA"},
                                     {"L-ManpA", "L-ManA"},
                                     {"L-GalpA", "L-GalA"},
                                     {"L-GulpA", "L-GulA"},
                                     {"D-AltpA", "D-AltA"},
                                     {"L-AllpA", "L-AllA"},
                                     {"L-TalpA", "L-TalA"},
                                     {"D-IdopA", "D-IdoA"},
                                     {"D-Fucp", "D-Fuc"},
                                     {"L-Quip", "L-Qui"},
                                     {"D-Rhap", "D-Rha"},
                                     {"L-6dGulp", "L-6dGul"},
                                     {"D-6dAltp", "D-6dAlt"},
                                     {"L-6dTalp", "L-6dTal"},
                                     {"L-QuipNAc", "L-QuiNAc"},
                                     {"D-RhapNAc", "D-RhaNAc"},
                                     {"D-6dAltpNAc", "D-6dAltNAc"},
                                     {"L-6dTalpNAc", "L-6dTalNAc"},
                                     {"D-FucpNAc", "D-FucNAc"},
                                     {"L-Olip", "L-Oli"},
                                     {"L-Tyvp", "L-Tyv"},
                                     {"L-Abep", "L-Abe"},
                                     {"L-Parp", "L-Par"},
                                     {"L-Digp", "L-Dig"},
                                     {"D-Colp", "D-Col"},
                                     {"D-Arap", "D-Ara"},
                                     {"L-Lyxp", "L-Lyx"},
                                     {"L-Xylp", "L-Xyl"},
                                     {"L-Ribp", "L-Rib"},
                                     {"L-Neu5Acp", "L-Neu5Ac"},
                                     {"L-Neu5Gcp", "L-Neu5Gc"},
                                     {"L-Kdnp", "L-Kdn"},
                                     {"L-Bacp", "L-Bac"},
                                     {"L-Kdop", "L-Kdo"},
                                     {"L-Dhap", "L-Dha"},
                                     {"L-MurpNAc", "L-MurNAc"},
                                     {"L-MurNGcp", "L-MurNGc"},
                                     {"L-Murp", "L-Mur"},
                                     {"D-Apip", "D-Api"},
                                     {"L-Frup", "L-Fru"},
                                     {"L-Tagp", "L-Tag"},
                                     {"D-Sorp", "D-Sor"},
                                     {"L-Psip", "L-Psi"},
                                     {"L-Glcf", "L-Glcf"},
                                     {"L-Manf", "L-Manf"},
                                     {"L-Galf", "L-Galf"},
                                     {"L-Gulf", "L-Gulf"},
                                     {"D-Altf", "D-Altf"},
                                     {"L-Allf", "L-Allf"},
                                     {"L-Talf", "L-Talf"},
                                     {"D-Idof", "D-Idof"},
                                     {"L-GlcfNAc", "L-GlcfNAc"},
                                     {"L-GalfNAc", "L-GalfNAc"},
                                     {"L-ManfNAc", "L-ManfNAc"},
                                     {"L-GulfNAc", "L-GulfNAc"},
                                     {"D-AltfNAc", "D-AltfNAc"},
                                     {"L-AllfNAc", "L-AllfNAc"},
                                     {"L-TalfNAc", "L-TalfNAc"},
                                     {"D-IdofNAc", "D-IdofNAc"},
                                     {"L-GlcfN", "L-GlcfN"},
                                     {"L-ManfN", "L-ManfN"},
                                     {"L-GalfN", "L-GalfN"},
                                     {"L-GulfN", "L-GulfN"},
                                     {"D-AltfN", "D-AltfN"},
                                     {"L-AllfN", "L-AllfN"},
                                     {"L-TalfN", "L-TalfN"},
                                     {"D-IdofN", "D-IdofN"},
                                     {"L-GlcfA", "L-GlcfA"},
                                     {"L-ManfA", "L-ManfA"},
                                     {"L-GalfA", "L-GalfA"},
                                     {"L-GulfA", "L-GulfA"},
                                     {"D-AltfA", "D-AltfA"},
                                     {"L-AllfA", "L-AllfA"},
                                     {"L-TalfA", "L-TalfA"},
                                     {"D-IdofA", "D-IdofA"},
                                     {"D-Fucf", "D-Fucf"},
                                     {"L-Quif", "L-Quif"},
                                     {"D-Rhaf", "D-Rhaf"},
                                     {"L-6dGulf", "L-6dGulf"},
                                     {"D-6dAltf", "D-6dAltf"},
                                     {"L-6dTalf", "L-6dTalf"},
                                     {"L-QuifNAc", "L-QuifNAc"},
                                     {"D-RhafNAc", "D-RhafNAc"},
                                     {"D-6dAltfNAc", "D-6dAltfNAc"},
                                     {"L-6dTalfNAc", "L-6dTalfNAc"},
                                     {"D-FucfNAc", "D-FucfNAc"},
                                     {"L-Olif", "L-Olif"},
                                     {"L-Tyvf", "L-Tyvf"},
                                     {"L-Abef", "L-Abef"},
                                     {"L-Parf", "L-Parf"},
                                     {"L-Digf", "L-Digf"},
                                     {"D-Colf", "D-Colf"},
                                     {"D-Araf", "D-Araf"},
                                     {"L-Lyxf", "L-Lyxf"},
                                     {"L-Xylf", "L-Xylf"},
                                     {"L-Ribf", "L-Ribf"},
                                     {"L-Neuf5Ac", "L-Neuf5Ac"},
                                     {"L-Neuf5Gc", "L-Neuf5Gc"},
                                     {"L-Kdnf", "L-Kdnf"},
                                     {"L-Bacf", "L-Bacf"},
                                     {"L-Kdof", "L-Kdof"},
                                     {"L-Dhaf", "L-Dhaf"},
                                     {"L-MurfNAc", "L-MurfNAc"},
                                     {"L-MurfNGc", "L-MurfNGc"},
                                     {"L-Murf", "L-Murf"},
                                     {"D-Apif", "D-Apif"},
                                     {"L-Fruf", "L-Fruf"},
                                     {"L-Tagf", "L-Tagf"},
                                     {"D-Sorf", "D-Sorf"},
                                     {"L-Psif", "L-Psif"}};
inline const Pairs wurcs_table = {
    {"L-Glc", "^a1211h-1[abx]_1-5(?!_2\\*N(CC/3=O)?|_3\\*OC\\^RCO/4=O/3C)"},
    {"L-Man", "^a2211h-1[abx]_1-5(?!_2\\*N(CC/3=O)?)"},
    {"L-Gal", "^a1221h-1[abx]_1-5(?!_2\\*N(CC/3=O)?)"},
    {"L-Gul", "^a1121h-1[abx]_1-5(?!_2\\*N(CC/3=O)?)"},
    {"D-Alt", "^a1222h-1[abx]_1-5(?!_2\\*N(CC/3=O)?)"},
    {"L-All", "^a1111h-1[abx]_1-5(?!_2\\*N(CC/3=O)?)"},
    {"L-Tal", "^a2221h-1[abx]_1-5(?!_2\\*N(CC/3=O)?)"},
    {"D-Ido", "^a1212h-1[abx]_1-5(?!_2\\*N(CC/3=O)?)"},
    {"L-GlcNAc", "^a1211h-1[abx]_1-5_2\\*NCC/3=O(?!_3\\*OC\\^RCO/4=O/3C)"},
    {"L-GalNAc", "^a1221h-1[abx]_1-5_2\\*NCC/3=O"},
    {"L-ManNAc", "^a5211h-1[abx]_1-5_2\\*NCC/3=O"},
    {"L-ManNAc", "^a2211h-1[abx]_1-5_2\\*NCC/3=O"},
    {"L-GulNAc", "^a1121h-1[abx]_1-5_2\\*NCC/3=O"},
    {"D-AltNAc", "^a1222h-1[abx]_1-5_2\\*NCC/3=O"},
    {"L-AllNAc", "^a1111h-1[abx]_1-5_2\\*NCC/3=O"},
    {"L-TalNAc", "^a2221h-1[abx]_1-5_2\\*NCC/3=O"},
    {"D-IdoNAc", "^a1212h-1[abx]_1-5_2\\*NCC/3=O"},
    {"L-GlcN", "^a1211h-1[abx]_1-5_2\\*N(?!CCO?/3=O(_3\\*OC\\^RCO/4=O/3C)?)"},
    {"L-ManN", "^a2211h-1[abx]_1-5_2\\*N(?!CC/3=O)"},
    {"L-GalN", "^a1221h-1[abx]_1-5_2\\*N(?!CC/3=O)"},
    {"L-GulN", "^a1121h-1[abx]_1-5_2\\*N(?!CC/3=O)"},
    {"D-AltN", "^a1222h-1[abx]_1-5_2\\*N(?!CC/3=O)"},
    {"L-AllN", "^a1111h-1[abx]_1-5_2\\*N(?!CC/3=O)"},
    {"L-TalN", "^a2221h-1[abx]_1-5_2\\*N(?!CC/3=O)"},
    {"D-IdoN", "^a1212h-1[abx]_1-5_2\\*N(?!CC/3=O)"},
    {"L-GlcA", "^a1211A-1[abx]_1-5"},
    {"L-ManA", "^a2211A-1[abx]_1-5"},
    {"L-GalA", "^a1221A-1[abx]_1-5"},
    {"L-GulA", "^a1121A-1[abx]_1-5"},
    {"D-AltA", "^a1222A-1[abx]_1-5"},
    {"L-AllA", "^a1111A-1[abx]_1-5"},
    {"L-TalA", "^a2221A-1[abx]_1-5"},
    {"D-IdoA", "^a1212A-1[abx]_1-5"},
    {"D-Fuc", "^a2112m-1[abx]_1-5(?!_2\\*NCC/3=O)"},
    {"D-Fuc", "^a21d2m-1[abx]_1-5(?!_2\\*NCC/3=O)"},
    {"L-Qui", "^a1211m-1[abx]_1-5(?!_2\\*NCC/3=O|_2\\*N_4\\*N)"},
    {"D-Rha", "^a1122m-1[abx]_1-5(?!_2\\*NCC/3=O)"},
    {"L-6dGul", "^a1121m-1[abx]_1-5(?!_2\\*NCC/3=O)"},
    {"D-6dAlt", "^a1222m-1[abx]_1-5(?!_2\\*NCC/3=O)"},
    {"L-6dTal", "^a2221m-1[abx]_1-5(?!_2\\*NCC/3=O)"},
    {"D-FucNAc", "^a2112m-1[abx]_1-5_2\\*NCC/3=O"},
    {"L-QuiNAc", "^a1211m-1[abx]_1-5_2\\*NCC/3=O"},
    {"D-RhaNAc", "^a1122m-1[abx]_1-5_2\\*NCC/3=O"},
    {"D-6dAltNAc", "^a1222m-1[abx]_1-5_2\\*NCC/3=O"},
    {"L-6dTalNAc", "^a2221m-1[abx]_1-5_2\\*NCC/3=O"},
    {"L-Oli", "^ad211m-1[abx]_1-5"},
    {"L-Tyv", "^a2d11m-1[abx]_1-5"},
    {"L-Par", "^a1d11m-1[abx]_1-5"},
    {"L-Dig", "^ad111m-1[abx]_1-5"},
    {"D-Ara", "^a122h-1[abx]_1-[45]"},
    {"L-Lyx", "^a112h-1[abx]_1-[45]"},
    {"L-Xyl", "^a121h-1[abx]_1-[45]"},
    {"L-Rib", "^a111h-1[abx]_1-[45]"},
    {"L-Neu5Ac", "^Aad12211h-2[abx]_2-6.*_5\\*NCC/3=O"},
    {"L-Neu5Gc", "^Aad12211h-2[abx]_2-6.*_5\\*NCCO/3=O"},
    {"L-Kdn", "^Aad12211h-2[abx]_2-6(?!.*_5\\*N(CC(O)?/3=O)?)"},
    {"L-Bac", "^a1211m-1[abx]_1-5_2\\*N_4\\*N"},
    {"L-Kdo", "^Aad2211h-2[abx]_2-6"},
    {"L-Dha", "^Aad221A-2[abx]_2-6"},
    {"L-MurNAc", "^a1211h-1[abx]_1-5_2\\*NCC/3=O_3\\*OC\\^RCO/4=O/3C"},
    {"L-MurNGc", "^a1211h-1[abx]_1-5_2\\*NCCO/3=O_3\\*OC\\^RCO/4=O/3C"},
    {"L-Mur", "^a1211h-1[abx]_1-5_3\\*OC\\^RCO/4=O/3C"},
    {"L-Fru", "^ha211h-2[abx]_2-6"},
    {"L-Tag", "^ha221h-2[abx]_2-6"},
    {"D-Sor", "^ha212h-2[abx]_2-6"},
    {"L-Psi", "^ha111h-2[abx]_2-6"},
    {"Glc", "^a2122h-1[abx]_1-5(?!_2\\*N(CC/3=O)?|_3\\*OC\\^RCO/4=O/3C)"},
    {"Man", "^a1122h-1[abx]_1-5(?!_2\\*N(CC/3=O)?)"},
    {"Gal", "^a2112h-1[abx]_1-5(?!_2\\*N(CC/3=O)?)"},
    {"Gul", "^a2212h-1[abx]_1-5(?!_2\\*N(CC/3=O)?)"},
    {"Alt", "^a2111h-1[abx]_1-5(?!_2\\*N(CC/3=O)?)"},
    {"All", "^a2222h-1[abx]_1-5(?!_2\\*N(CC/3=O)?)"},
    {"Tal", "^a1112h-1[abx]_1-5(?!_2\\*N(CC/3=O)?)"},
    {"Ido", "^a2121h-1[abx]_1-5(?!_2\\*N(CC/3=O)?)"},
    {"GlcNAc", "^a2122h-1[abx]_1-5_2\\*NCC/3=O(?!_3\\*OC\\^RCO/4=O/3C)"},
    {"GalNAc", "^a2112h-1[abx]_1-5_2\\*NCC/3=O"},
    {"ManNAc", "^a5122h-1[abx]_1-5_2\\*NCC/3=O"},
    {"ManNAc", "^a1122h-1[abx]_1-5_2\\*NCC/3=O"},
    {"GulNAc", "^a2212h-1[abx]_1-5_2\\*NCC/3=O"},
    {"AltNAc", "^a2111h-1[abx]_1-5_2\\*NCC/3=O"},
    {"AllNAc", "^a2222h-1[abx]_1-5_2\\*NCC/3=O"},
    {"TalNAc", "^a1112h-1[abx]_1-5_2\\*NCC/3=O"},
    {"IdoNAc", "^a2121h-1[abx]_1-5_2\\*NCC/3=O"},
    {"GlcN", "^a2122h-1[abx]_1-5_2\\*N(?!CCO?/3=O(_3\\*OC\\^RCO/4=O/3C)?)"},
    {"ManN", "^a1122h-1[abx]_1-5_2\\*N(?!CC/3=O)"},
    {"GalN", "^a2112h-1[abx]_1-5_2\\*N(?!CC/3=O)"},
    {"GulN", "^a2212h-1[abx]_1-5_2\\*N(?!CC/3=O)"},
    {"AltN", "^a2111h-1[abx]_1-5_2\\*N(?!CC/3=O)"},
    {"AllN", "^a2222h-1[abx]_1-5_2\\*N(?!CC/3=O)"},
    {"TalN", "^a1112h-1[abx]_1-5_2\\*N(?!CC/3=O)"},
    {"IdoN", "^a2121h-1[abx]_1-5_2\\*N(?!CC/3=O)"},
    {"GlcA", "^a2122A-1[abx]_1-5"},
    {"ManA", "^a1122A-1[abx]_1-5"},
    {"GalA", "^a2112A-1[abx]_1-5"},
    {"GulA", "^a2212A-1[abx]_1-5"},
    {"AltA", "^a2111A-1[abx]_1-5"},
    {"AllA", "^a2222A-1[abx]_1-5"},
    {"TalA", "^a1112A-1[abx]_1-5"},
    {"IdoA", "^a2121A-1[abx]_1-5"},
    {"Fuc", "^a1221m-1[abx]_1-5(?!_2\\*NCC/3=O)"},
    {"Fuc", "^a12d1m-1[abx]_1-5(?!_2\\*NCC/3=O)"},
    {"Qui", "^a2122m-1[abx]_1-5(?!_2\\*NCC/3=O|_2\\*N_4\\*N)"},
    {"Rha", "^a2211m-1[abx]_1-5(?!_2\\*NCC/3=O)"},
    {"6dGul", "^a2212m-1[abx]_1-5(?!_2\\*NCC/3=O)"},
    {"6dAlt", "^a2111m-1[abx]_1-5(?!_2\\*NCC/3=O)"},
    {"6dTal", "^a1112m-1[abx]_1-5(?!_2\\*NCC/3=O)"},
    {"FucNAc", "^a1221m-1[abx]_1-5_2\\*NCC/3=O"},
    {"QuiNAc", "^a2122m-1[abx]_1-5_2\\*NCC/3=O"},
    {"RhaNAc", "^a2211m-1[abx]_1-5_2\\*NCC/3=O"},
    {"6dAltNAc", "^a2111m-1[abx]_1-5_2\\*NCC/3=O"},
    {"6dTalNAc", "^a1112m-1[abx]_1-5_2\\*NCC/3=O"},
    {"Oli", "^ad122m-1[abx]_1-5"},
    {"Tyv", "^a1d22m-1[abx]_1-5"},
    {"Abe", "^a2d12m-1[abx]_1-5"},
    {"Par", "^a2d22m-1[abx]_1-5"},
    {"Dig", "^ad222m-1[abx]_1-5"},
    {"Col", "^a1d21m-1[abx]_1-5"},
    {"Ara", "^a211h-1[abx]_1-[45]"},
    {"Lyx", "^a221h-1[abx]_1-[45]"},
    {"Xyl", "^a212h-1[abx]_1-[45]"},
    {"Rib", "^a222h-1[abx]_1-[45]"},
    {"NeuAc", "^Aadxxxxxh-2[abx]_2-6(?=.*_5\\*NCC/3=O)"},
    {"NeuGc", "^Aadxxxxxh-2[abx]_2-6(?=.*_5\\*NCCO/3=O)"},
    {"gNeu", "^Aadxxxxxh-2[abx]_2-6(?=.*_5\\*N(?!CC(O)?/3=O))"},
    {"gKdn", "^Aadxxxxxh-2[abx]_2-6(?!.*_5\\*N)"},
    {"Neu5Ac", "^Aad21122h-2[abx]_2-6.*_5\\*NCC/3=O"},
    {"Neu5Gc", "^Aad21122h-2[abx]_2-6.*_5\\*NCCO/3=O"},
    {"Kdn", "^Aad21122h-2[abx]_2-6(?!.*_5\\*N(CC(O)?/3=O)?)"},
    {"Neu", "^Aad21122h-2[abx]_2-6(?=.*_5\\*N(?!CC(O)?/3=O))"},
    {"Pse", "^had22111m-2[abx]_2-6_5\\*N_7\\*N"},
    {"Leg", "^Aad21122m-2[abx]_2-6_5\\*N_7\\*N"},
    {"Aci", "^Aad21111m-2[abx]_2-6_5\\*N_7\\*N"},
    {"4eLeg", "^Aad11122m-2[abx]_2-6_5\\*N_7\\*N"},
    {"Bac", "^a2122m-1[abx]_1-5_2\\*N_4\\*N"},
    {"LDmanHep", "^a11221h-1[abx]_1-5"},
    {"Kdo", "^Aad1122h-2[abx]_2-6"},
    {"Dha", "^Aad112A-2[abx]_2-6"},
    {"DDmanHep", "^a11222h-1[abx]_1-5"},
    {"MurNAc", "^a2122h-1[abx]_1-5_2\\*NCC/3=O_3\\*OC\\^RCO/4=O/3C"},
    {"MurNGc", "^a2122h-1[abx]_1-5_2\\*NCCO/3=O_3\\*OC\\^RCO/4=O/3C"},
    {"Mur", "^a2122h-1[abx]_1-5_3\\*OC\\^RCO/4=O/3C"},
    {"HexNAc", "^axxxxh-1[abx]_1-5_2\\*NCC/3=O"},
    {"HexN", "^axxxxh-1[abx]_1-5_2\\*N(?!CC/3=O)"},
    {"HexA", "^axxxxA-1[abx]_1-5"},
    {"Hex", "^axxxxh-1[abx]_1-5"},
    {"dHexNAc", "^axxxxm-1[abx]_1-5_2\\*NCC/3=O"},
    {"dHex", "^axxxxm-1[abx]_1-5"},
    {"Pen", "^axxxh-1[abx]_1-5"},
    {"dHexNAc", "^a2112m-1[abx]_1-5_2\\*NCC/3=O"},
    {"dHex", "^a2112m-1[abx]_1-5"},
    {"Fru", "^ha122h-2[abx]_2-6"},
    {"Tag", "^ha112h-2[abx]_2-6"},
    {"Sor", "^ha121h-2[abx]_2-6"},
    {"Psi", "^ha222h-2[abx]_2-6"}};
inline const Pairs wurcs_unknown_table = {
    {"L-Neu5Ac", "^Aad12211h-2[abx]_2-\\?(?=.*_5\\*NCC/3=O)"},
    {"L-Neu5Gc", "^Aad12211h-2[abx]_2-\\?(?=.*_5\\*NCCO/3=O)"},
    {"L-Kdn", "^Aad12211h-2[abx]_2-\\?(?!.*_5\\*N)"},
    {"L-GlcNAc", "^a1211h-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"L-GalNAc", "^a1221h-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"L-ManNAc", "^a2211h-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"L-GulNAc", "^a1121h-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"D-AltNAc", "^a1222h-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"L-AllNAc", "^a1111h-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"L-TalNAc", "^a2221h-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"D-IdoNAc", "^a1212h-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"L-GlcN", "^a1211h-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"L-ManN", "^a2211h-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"L-GalN", "^a1221h-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"L-GulN", "^a1121h-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"D-AltN", "^a1222h-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"L-AllN", "^a1111h-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"L-TalN", "^a2221h-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"D-IdoN", "^a1212h-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"L-GlcA", "^a1211A-1[abx]_1-\\?"},
    {"L-ManA", "^a2211A-1[abx]_1-\\?"},
    {"L-GalA", "^a1221A-1[abx]_1-\\?"},
    {"L-GulA", "^a1121A-1[abx]_1-\\?"},
    {"D-AltA", "^a1222A-1[abx]_1-\\?"},
    {"L-AllA", "^a1111A-1[abx]_1-\\?"},
    {"L-TalA", "^a2221A-1[abx]_1-\\?"},
    {"D-IdoA", "^a1212A-1[abx]_1-\\?"},
    {"L-Glc", "^a1211h-1[abx]_1-\\?(?!_2\\*N(CC/3=O)?)"},
    {"L-Man", "^a2211h-1[abx]_1-\\?(?!_2\\*N(CC/3=O)?)"},
    {"L-Gal", "^a1221h-1[abx]_1-\\?(?!_2\\*N(CC/3=O)?)"},
    {"L-Gul", "^a1121h-1[abx]_1-\\?(?!_2\\*N(CC/3=O)?)"},
    {"D-Alt", "^a1222h-1[abx]_1-\\?(?!_2\\*N(CC/3=O)?)"},
    {"L-All", "^a1111h-1[abx]_1-\\?(?!_2\\*N(CC/3=O)?)"},
    {"L-Tal", "^a2221h-1[abx]_1-\\?(?!_2\\*N(CC/3=O)?)"},
    {"D-Ido", "^a1212h-1[abx]_1-\\?(?!_2\\*N(CC/3=O)?)"},
    {"D-FucNAc", "^a2112m-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"L-QuiNAc", "^a1211m-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"D-RhaNAc", "^a1122m-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"D-6dAltNAc", "^a1222m-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"L-6dTalNAc", "^a2221m-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"D-Fuc", "^a2112m-1[abx]_1-\\?(?!_2\\*NCC/3=O)"},
    {"L-Qui", "^a1211m-1[abx]_1-\\?(?!_2\\*NCC/3=O|_2\\*N_4\\*N)"},
    {"D-Rha", "^a1122m-1[abx]_1-\\?(?!_2\\*NCC/3=O)"},
    {"L-6dGul", "^a1121m-1[abx]_1-\\?"},
    {"D-6dAlt", "^a1222m-1[abx]_1-\\?(?!_2\\*NCC/3=O)"},
    {"L-6dTal", "^a2221m-1[abx]_1-\\?(?!_2\\*NCC/3=O)"},
    {"L-Oli", "^ad211m-1[abx]_1-\\?"},
    {"L-Tyv", "^a2d11m-1[abx]_1-\\?"},
    {"L-Par", "^a1d11m-1[abx]_1-\\?"},
    {"L-Dig", "^ad111m-1[abx]_1-\\?"},
    {"D-Ara", "^a122h-1[abx]_1-\\?"},
    {"L-Lyx", "^a112h-1[abx]_1-\\?"},
    {"L-Xyl", "^a121h-1[abx]_1-\\?"},
    {"L-Rib", "^a111h-1[abx]_1-\\?"},
    {"Neu5Ac", "^Aad21122h-2[abx]_2-\\?(?=.*_5\\*NCC/3=O)"},
    {"Neu5Gc", "^Aad21122h-2[abx]_2-\\?(?=.*_5\\*NCCO/3=O)"},
    {"Neu", "^Aad21122h-2[abx]_2-\\?(?=.*_5\\*N(?!CC(O)?/3=O))"},
    {"Kdn", "^Aad21122h-2[abx]_2-\\?(?!.*_5\\*N)"},
    {"NeuAc", "^Aadxxxxxh-2[abx]_2-\\?(?=.*_5\\*NCC/3=O)"},
    {"NeuGc", "^Aadxxxxxh-2[abx]_2-\\?(?=.*_5\\*NCCO/3=O)"},
    {"gNeu", "^Aadxxxxxh-2[abx]_2-\\?(?=.*_5\\*N(?!CC(O)?/3=O))"},
    {"gKdn", "^Aadxxxxxh-2[abx]_2-\\?(?!.*_5\\*N)"},
    {"GlcNAc", "^a2122h-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"GalNAc", "^a2112h-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"ManNAc", "^a1122h-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"GulNAc", "^a2212h-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"AltNAc", "^a2111h-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"AllNAc", "^a2222h-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"TalNAc", "^a1112h-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"IdoNAc", "^a2121h-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"GlcN", "^a2122h-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"ManN", "^a1122h-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"GalN", "^a2112h-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"GulN", "^a2212h-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"AltN", "^a2111h-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"AllN", "^a2222h-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"TalN", "^a1112h-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"IdoN", "^a2121h-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"GlcA", "^a2122A-1[abx]_1-\\?"},
    {"ManA", "^a1122A-1[abx]_1-\\?"},
    {"GalA", "^a2112A-1[abx]_1-\\?"},
    {"GulA", "^a2212A-1[abx]_1-\\?"},
    {"AltA", "^a2111A-1[abx]_1-\\?"},
    {"AllA", "^a2222A-1[abx]_1-\\?"},
    {"TalA", "^a1112A-1[abx]_1-\\?"},
    {"IdoA", "^a2121A-1[abx]_1-\\?"},
    {"Glc", "^a2122h-1[abx]_1-\\?(?!_2\\*N(CC/3=O)?)"},
    {"Man", "^a1122h-1[abx]_1-\\?(?!_2\\*N(CC/3=O)?)"},
    {"Gal", "^a2112h-1[abx]_1-\\?(?!_2\\*N(CC/3=O)?)"},
    {"Gul", "^a2212h-1[abx]_1-\\?(?!_2\\*N(CC/3=O)?)"},
    {"Alt", "^a2111h-1[abx]_1-\\?(?!_2\\*N(CC/3=O)?)"},
    {"All", "^a2222h-1[abx]_1-\\?(?!_2\\*N(CC/3=O)?)"},
    {"Tal", "^a1112h-1[abx]_1-\\?(?!_2\\*N(CC/3=O)?)"},
    {"Ido", "^a2121h-1[abx]_1-\\?(?!_2\\*N(CC/3=O)?)"},
    {"FucNAc", "^a1221m-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"QuiNAc", "^a2122m-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"RhaNAc", "^a2211m-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"6dAltNAc", "^a2111m-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"6dTalNAc", "^a1112m-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"Fuc", "^a1221m-1[abx]_1-\\?(?!_2\\*NCC/3=O)"},
    {"Qui", "^a2122m-1[abx]_1-\\?(?!_2\\*NCC/3=O|_2\\*N_4\\*N)"},
    {"Rha", "^a2211m-1[abx]_1-\\?(?!_2\\*NCC/3=O)"},
    {"6dGul", "^a2212m-1[abx]_1-\\?"},
    {"6dAlt", "^a2111m-1[abx]_1-\\?(?!_2\\*NCC/3=O)"},
    {"6dTal", "^a1112m-1[abx]_1-\\?(?!_2\\*NCC/3=O)"},
    {"Oli", "^ad122m-1[abx]_1-\\?"},
    {"Tyv", "^a1d22m-1[abx]_1-\\?"},
    {"Abe", "^a2d12m-1[abx]_1-\\?"},
    {"Par", "^a2d22m-1[abx]_1-\\?"},
    {"Dig", "^ad222m-1[abx]_1-\\?"},
    {"Col", "^a1d21m-1[abx]_1-\\?"},
    {"Ara", "^a211h-1[abx]_1-\\?"},
    {"Lyx", "^a221h-1[abx]_1-\\?"},
    {"Xyl", "^a212h-1[abx]_1-\\?"},
    {"Rib", "^a222h-1[abx]_1-\\?"},
    {"HexNAc", "^axxxxh-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"HexN", "^axxxxh-1[abx]_1-\\?_2\\*N(?!CC/3=O)"},
    {"HexA", "^axxxxA-1[abx]_1-\\?"},
    {"Hex", "^axxxxh-1[abx]_1-\\?"},
    {"dHexNAc", "^axxxxm-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"dHex", "^axxxxm-1[abx]_1-\\?"},
    {"Pen", "^axxxh-1[abx]_1-\\?"},
    {"dHexNAc", "^a2112m-1[abx]_1-\\?_2\\*NCC/3=O"},
    {"dHex", "^a2112m-1[abx]_1-\\?"},
    {"dHex", "^a4334m-1[abx]_1-\\?"}};
inline const Pairs wurcs_ambiguous_table = {
    {"L-Neu5Ac", "^AUd12211h.*_5\\*NCC/3=O"},
    {"L-Neu5Gc", "^AUd12211h.*_5\\*NCCO/3=O"},
    {"L-Kdn", "^AUd12211h"},
    {"L-GlcNAc", "^u1211h_2\\*NCC/3=O"},
    {"L-GalNAc", "^u1221h_2\\*NCC/3=O"},
    {"L-ManNAc", "^u2211h_2\\*NCC/3=O"},
    {"L-GulNAc", "^u1121h_2\\*NCC/3=O"},
    {"D-AltNAc", "^u1222h_2\\*NCC/3=O"},
    {"L-AllNAc", "^u1111h_2\\*NCC/3=O"},
    {"L-TalNAc", "^u2221h_2\\*NCC/3=O"},
    {"D-IdoNAc", "^u1212h_2\\*NCC/3=O"},
    {"L-GlcN", "^u1211h_2\\*N(?!CC/3=O)"},
    {"L-ManN", "^u2211h_2\\*N(?!CC/3=O)"},
    {"L-GalN", "^u1221h_2\\*N(?!CC/3=O)"},
    {"L-GulN", "^u1121h_2\\*N(?!CC/3=O)"},
    {"D-AltN", "^u1222h_2\\*N(?!CC/3=O)"},
    {"L-AllN", "^u1111h_2\\*N(?!CC/3=O)"},
    {"L-TalN", "^u2221h_2\\*N(?!CC/3=O)"},
    {"D-IdoN", "^u1212h_2\\*N(?!CC/3=O)"},
    {"L-GlcA", "^u1211A"},
    {"L-ManA", "^u2211A"},
    {"L-GalA", "^u1221A"},
    {"L-GulA", "^u1121A"},
    {"D-AltA", "^u1222A"},
    {"L-AllA", "^u1111A"},
    {"L-TalA", "^u2221A"},
    {"D-IdoA", "^u1212A"},
    {"L-Glc", "^u1211h(?!_2\\*N(CC/3=O)?)"},
    {"L-Man", "^u2211h(?!_2\\*N(CC/3=O)?)"},
    {"L-Gal", "^u1221h(?!_2\\*N(CC/3=O)?)"},
    {"L-Gul", "^u1121h(?!_2\\*N(CC/3=O)?)"},
    {"D-Alt", "^u1222h(?!_2\\*N(CC/3=O)?)"},
    {"L-All", "^u1111h(?!_2\\*N(CC/3=O)?)"},
    {"L-Tal", "^u2221h(?!_2\\*N(CC/3=O)?)"},
    {"D-Ido", "^u1212h(?!_2\\*N(CC/3=O)?)"},
    {"D-FucNAc", "^u2112m_2\\*NCC/3=O"},
    {"L-QuiNAc", "^u1211m_2\\*NCC/3=O"},
    {"D-RhaNAc", "^u1122m_2\\*NCC/3=O"},
    {"D-6dAltNAc", "^u1222m_2\\*NCC/3=O"},
    {"L-6dTalNAc", "^u2221m_2\\*NCC/3=O"},
    {"D-Fuc", "^u2112m(?!_2\\*NCC/3=O)"},
    {"L-Qui", "^u1211m(?!_2\\*NCC/3=O|_2\\*N_4\\*N)"},
    {"D-Rha", "^u1122m(?!_2\\*NCC/3=O)"},
    {"L-6dGul", "^u1121m"},
    {"D-6dAlt", "^u1222m(?!_2\\*NCC/3=O)"},
    {"L-6dTal", "^u2221m(?!_2\\*NCC/3=O)"},
    {"L-Oli", "^ud211m"},
    {"L-Tyv", "^u2d11m"},
    {"L-Par", "^u1d11m"},
    {"L-Dig", "^ud111m"},
    {"D-Ara", "^u122h"},
    {"L-Lyx", "^u112h"},
    {"L-Xyl", "^u121h"},
    {"L-Rib", "^u111h"},
    {"NeuAc", "^AUdxxxxxh(?=.*_5\\*NCC/3=O)"},
    {"NeuGc", "^AUdxxxxxh(?=.*_5\\*NCCO/3=O)"},
    {"gNeu", "^AUdxxxxxh(?=.*_5\\*N(?!CC(O)?/3=O))"},
    {"gKdn", "^AUdxxxxxh(?!.*_5\\*N)"},
    {"Neu5Ac", "^AUd21122h.*_5\\*NCC/3=O"},
    {"Neu5Gc", "^AUd21122h.*_5\\*NCCO/3=O"},
    {"Neu", "^AUd21122h.*_5\\*N"},
    {"Kdn", "^AUd21122h"},
    {"GlcNAc", "^u2122h_2\\*NCC/3=O"},
    {"GalNAc", "^u2112h_2\\*NCC/3=O"},
    {"ManNAc", "^u1122h_2\\*NCC/3=O"},
    {"GulNAc", "^u2212h_2\\*NCC/3=O"},
    {"AltNAc", "^u2111h_2\\*NCC/3=O"},
    {"AllNAc", "^u2222h_2\\*NCC/3=O"},
    {"TalNAc", "^u1112h_2\\*NCC/3=O"},
    {"IdoNAc", "^u2121h_2\\*NCC/3=O"},
    {"GlcN", "^u2122h_2\\*N(?!CC/3=O)"},
    {"ManN", "^u1122h_2\\*N(?!CC/3=O)"},
    {"GalN", "^u2112h_2\\*N(?!CC/3=O)"},
    {"GulN", "^u2212h_2\\*N(?!CC/3=O)"},
    {"AltN", "^u2111h_2\\*N(?!CC/3=O)"},
    {"AllN", "^u2222h_2\\*N(?!CC/3=O)"},
    {"TalN", "^u1112h_2\\*N(?!CC/3=O)"},
    {"IdoN", "^u2121h_2\\*N(?!CC/3=O)"},
    {"GlcA", "^u2122A"},
    {"ManA", "^u1122A"},
    {"GalA", "^u2112A"},
    {"GulA", "^u2212A"},
    {"AltA", "^u2111A"},
    {"AllA", "^u2222A"},
    {"TalA", "^u1112A"},
    {"IdoA", "^u2121A"},
    {"Glc", "^u2122h(?!_2\\*N(CC/3=O)?)"},
    {"Man", "^u1122h(?!_2\\*N(CC/3=O)?)"},
    {"Gal", "^u2112h(?!_2\\*N(CC/3=O)?)"},
    {"Gul", "^u2212h(?!_2\\*N(CC/3=O)?)"},
    {"Alt", "^u2111h(?!_2\\*N(CC/3=O)?)"},
    {"All", "^u2222h(?!_2\\*N(CC/3=O)?)"},
    {"Tal", "^u1112h(?!_2\\*N(CC/3=O)?)"},
    {"Ido", "^u2121h(?!_2\\*N(CC/3=O)?)"},
    {"FucNAc", "^u1221m_2\\*NCC/3=O"},
    {"QuiNAc", "^u2122m_2\\*NCC/3=O"},
    {"RhaNAc", "^u2211m_2\\*NCC/3=O"},
    {"6dAltNAc", "^u2111m_2\\*NCC/3=O"},
    {"6dTalNAc", "^u1112m_2\\*NCC/3=O"},
    {"Fuc", "^u1221m(?!_2\\*NCC/3=O)"},
    {"Qui", "^u2122m(?!_2\\*NCC/3=O|_2\\*N_4\\*N)"},
    {"Rha", "^u2211m(?!_2\\*NCC/3=O)"},
    {"6dGul", "^u2212m"},
    {"6dAlt", "^u2111m(?!_2\\*NCC/3=O)"},
    {"6dTal", "^u1112m(?!_2\\*NCC/3=O)"},
    {"Oli", "^ud122m"},
    {"Tyv", "^u1d22m"},
    {"Abe", "^u2d12m"},
    {"Par", "^u2d22m"},
    {"Dig", "^ud222m"},
    {"Col", "^u1d21m"},
    {"Ara", "^u211h"},
    {"Lyx", "^u221h"},
    {"Xyl", "^u212h"},
    {"Rib", "^u222h"},
    {"HexNAc", "^uxxxxh_2\\*NCC/3=O"},
    {"HexN", "^uxxxxh_2\\*N(?!CC/3=O)"},
    {"HexA", "^uxxxxA"},
    {"Hex", "^uxxxxh"},
    {"dHexNAc", "^uxxxxm_2\\*NCC/3=O"},
    {"dHex", "^uxxxxm"},
    {"Pen", "^uxxxh"},
    {"dHexNAc", "^u2112m_2\\*NCC/3=O"},
    {"dHex", "^u2112m"}};
inline const Pairs wurcs_alditol_table = {
    {"L-MurNAc", "^h1211h_2\\*NCC/3=O_3\\*OC\\^RCO/4=O/3C"},
    {"L-MurNGc", "^h1211h_2\\*NCCO/3=O_3\\*OC\\^RCO/4=O/3C"},
    {"L-Mur", "^h1211h_3\\*OC\\^RCO/4=O/3C"},
    {"L-GlcNAc", "^h1211h_2\\*NCC/3=O"},
    {"L-GalNAc", "^h1221h_2\\*NCC/3=O"},
    {"L-ManNAc", "^h2211h_2\\*NCC/3=O"},
    {"L-GulNAc", "^h1121h_2\\*NCC/3=O"},
    {"D-AltNAc", "^h1112h_5\\*NCC/3=O"},
    {"L-AllNAc", "^h1111h_2\\*NCC/3=O"},
    {"L-TalNAc", "^h2111h_5\\*NCC/3=O"},
    {"D-IdoNAc", "^h1212h_2\\*NCC/3=O"},
    {"L-GlcN", "^h1211h_2\\*N"},
    {"L-ManN", "^h2211h_2\\*N"},
    {"L-GalN", "^h1221h_2\\*N"},
    {"L-GulN", "^h1121h_2\\*N"},
    {"D-AltN", "^h1112h_5\\*N"},
    {"L-AllN", "^h1111h_2\\*N"},
    {"L-TalN", "^h2111h_5\\*N"},
    {"D-IdoN", "^h1212h_2\\*N"},
    {"L-Glc", "^h1211h"},
    {"L-Man", "^h2211h"},
    {"L-Gal", "^h1221h"},
    {"L-Gul", "^h1121h"},
    {"D-Alt", "^h1112h"},
    {"L-All", "^h1111h"},
    {"L-Tal", "^h2111h"},
    {"D-Ido", "^h1212h"},
    {"D-FucNAc", "^h2112m_2\\*NCC/3=O"},
    {"L-QuiNAc", "^h1211m_2\\*NCC/3=O"},
    {"D-RhaNAc", "^h1122m_2\\*NCC/3=O"},
    {"D-6dAltNAc", "^h1222m_2\\*NCC/3=O"},
    {"L-6dTalNAc", "^h2221m_2\\*NCC/3=O"},
    {"L-Bac", "^h1211m_2\\*N_4\\*N"},
    {"D-Fuc", "^h2112m"},
    {"L-Qui", "^h1211m"},
    {"D-Rha", "^h1122m"},
    {"L-6dGul", "^h1121m"},
    {"D-6dAlt", "^h1222m"},
    {"L-6dTal", "^h2221m"},
    {"L-Oli", "^hd211m"},
    {"L-Tyv", "^h2d11m"},
    {"L-Par", "^h1d11m"},
    {"L-Dig", "^hd111m"},
    {"L-Lyx", "^h112h"},
    {"L-Xyl", "^h121h"},
    {"L-Rib", "^h111h"},
    {"L-Neu5Ac", "^hUd12211h_5\\*NCC/3=O"},
    {"L-Neu5Gc", "^hUd12211h_5\\*NCCO/3=O"},
    {"L-Kdn", "^hUd12211h"},
    {"L-Kdo", "^hUd2211h"},
    {"L-Dha", "^A211dUh"},
    {"L-Fru", "^hU211h"},
    {"L-Tag", "^hU221h"},
    {"D-Sor", "^hU212h"},
    {"L-Psi", "^hU111h"},
    {"MurNAc", "^h2122h_2\\*NCC/3=O_3\\*OC\\^RCO/4=O/3C"},
    {"MurNGc", "^h2122h_2\\*NCCO/3=O_3\\*OC\\^RCO/4=O/3C"},
    {"Mur", "^h2122h_3\\*OC\\^RCO/4=O/3C"},
    {"GlcNAc", "^h2122h_2\\*NCC/3=O"},
    {"GalNAc", "^h2112h_2\\*NCC/3=O"},
    {"ManNAc", "^h1122h_2\\*NCC/3=O"},
    {"GulNAc", "^h2212h_2\\*NCC/3=O"},
    {"AltNAc", "^h2221h_5\\*NCC/3=O"},
    {"AllNAc", "^h2222h_2\\*NCC/3=O"},
    {"TalNAc", "^h1222h_5\\*NCC/3=O"},
    {"IdoNAc", "^h2121h_2\\*NCC/3=O"},
    {"GlcN", "^h2122h_2\\*N"},
    {"ManN", "^h1122h_2\\*N"},
    {"GalN", "^h2112h_2\\*N"},
    {"GulN", "^h2212h_2\\*N"},
    {"AltN", "^h2221h_5\\*N"},
    {"AllN", "^h2222h_2\\*N"},
    {"TalN", "^h1222h_5\\*N"},
    {"IdoN", "^h2121h_2\\*N"},
    {"Glc", "^h2122h"},
    {"Man", "^h1122h"},
    {"Gal", "^h2112h"},
    {"Gul", "^h2212h"},
    {"Alt", "^h2221h"},
    {"All", "^h2222h"},
    {"Tal", "^h1222h"},
    {"Ido", "^h2121h"},
    {"FucNAc", "^h1221m_2\\*NCC/3=O"},
    {"QuiNAc", "^h2122m_2\\*NCC/3=O"},
    {"RhaNAc", "^h2211m_2\\*NCC/3=O"},
    {"6dAltNAc", "^h2111m_2\\*NCC/3=O"},
    {"6dTalNAc", "^h1112m_2\\*NCC/3=O"},
    {"Bac", "^h2122m_2\\*N_4\\*N"},
    {"Fuc", "^h1221m"},
    {"Qui", "^h2122m"},
    {"Rha", "^h2211m"},
    {"6dGul", "^h2212m"},
    {"6dAlt", "^h2111m"},
    {"6dTal", "^h1112m"},
    {"Oli", "^hd122m"},
    {"Tyv", "^h1d22m"},
    {"Abe", "^h2d12m"},
    {"Par", "^h2d22m"},
    {"Dig", "^hd222m"},
    {"Col", "^h1d21m"},
    {"Lyx", "^h221h"},
    {"Xyl", "^h212h"},
    {"Rib", "^h222h"},
    {"NeuAc", "^hUdxxxxxh(?=.*_5\\*NCC/3=O)"},
    {"NeuGc", "^hUdxxxxxh(?=.*_5\\*NCCO/3=O)"},
    {"gNeu", "^hUdxxxxxh(?=.*_5\\*N(?!CC(O)?/3=O))"},
    {"gKdn", "^hUdxxxxxh(?!.*_5\\*N)"},
    {"Neu5Ac", "^hUd21122h_5\\*NCC/3=O"},
    {"Neu5Gc", "^hUd21122h_5\\*NCCO/3=O"},
    {"Neu", "^hUd21122h_5\\*N"},
    {"Kdn", "^hUd21122h"},
    {"Pse", "^hUd22111m_5\\*N_7\\*N"},
    {"Leg", "^hUd21122m_5\\*N_7\\*N"},
    {"Aci", "^hUd21111m_5\\*N_7\\*N"},
    {"4eLeg", "^hUd11122m_5\\*N_7\\*N"},
    {"LDmanHep", "^h21122h"},
    {"Kdo", "^hUd1122h"},
    {"Dha", "^A122dUh"},
    {"DDmanHep", "^h11222h"},
    {"Fru", "^hU122h"},
    {"Tag", "^hU112h"},
    {"Sor", "^hU121h"},
    {"Psi", "^hU222h"},
    {"HexNAc", "^hxxxxh_2\\*NCC/3=O"},
    {"HexN", "^hxxxxh_2\\*N(?!CC/3=O)"},
    {"HexA", "^hxxxxA"},
    {"Hex", "^hxxxxh"},
    {"dHexNAc", "^hxxxxm_2\\*NCC/3=O"},
    {"dHex", "^hxxxxm"},
    {"Pen", "^hxxxh"}};
inline const Pairs wurcs_sub_table = {{"Me", "OC"},
                                      {"Ac", "OCC/3=O"},
                                      {"NAc", "NCC/3=O"},
                                      {"P", "(?:OPO/3O/3=O|PO/2O/2=O)"},
                                      {"S", "OSO/3=O/3=O"},
                                      {"Pyr", "OCCC/4=O/3=O"},
                                      {"PC", "OP(\\^X)?OCCNC/7C/7C/3O/3=O"},
                                      {"PPEtn", "OP(\\^X)?OP(\\^X)?OCCN/5O/5=O/3O/3=O"},
                                      {"PEtn", "OP(\\^X)?OCCN/3O/3=O"},
                                      {"N", "N"}};
struct CTMapping {
  std::string name, core, bounds;
  bool alditol;
  std::vector<std::string> subs;
};
inline const std::vector<CTMapping> glycoct_entries = {
    {"Glc", "dglc-HEX", "1:5", false, {}},
    {"Man", "dman-HEX", "1:5", false, {}},
    {"Gal", "dgal-HEX", "1:5", false, {}},
    {"Gul", "dgul-HEX", "1:5", false, {}},
    {"Alt", "lalt-HEX", "1:5", false, {}},
    {"All", "dall-HEX", "1:5", false, {}},
    {"Tal", "dtal-HEX", "1:5", false, {}},
    {"Ido", "lido-HEX", "1:5", false, {}},
    {"GlcNAc", "dglc-HEX", "1:5", false, {"n-acetyl\r2\r1"}},
    {"GalNAc", "dgal-HEX", "1:5", false, {"n-acetyl\r2\r1"}},
    {"ManNAc", "dman-HEX", "1:5", false, {"n-acetyl\r2\r1"}},
    {"GulNAc", "dgul-HEX", "1:5", false, {"n-acetyl\r2\r1"}},
    {"AltNAc", "lalt-HEX", "1:5", false, {"n-acetyl\r2\r1"}},
    {"AllNAc", "dall-HEX", "1:5", false, {"n-acetyl\r2\r1"}},
    {"TalNAc", "dtal-HEX", "1:5", false, {"n-acetyl\r2\r1"}},
    {"IdoNAc", "lido-HEX", "1:5", false, {"n-acetyl\r2\r1"}},
    {"GlcN", "dglc-HEX", "1:5", false, {"amino\r2\r1"}},
    {"ManN", "dman-HEX", "1:5", false, {"amino\r2\r1"}},
    {"GalN", "dgal-HEX", "1:5", false, {"amino\r2\r1"}},
    {"GulN", "dgul-HEX", "1:5", false, {"amino\r2\r1"}},
    {"AltN", "lalt-HEX", "1:5", false, {"amino\r2\r1"}},
    {"AllN", "dall-HEX", "1:5", false, {"amino\r2\r1"}},
    {"TalN", "dtal-HEX", "1:5", false, {"amino\r2\r1"}},
    {"IdoN", "lido-HEX", "1:5", false, {"amino\r2\r1"}},
    {"GlcA", "dglc-HEX|6:a", "1:5", false, {}},
    {"ManA", "dman-HEX|6:a", "1:5", false, {}},
    {"GalA", "dgal-HEX|6:a", "1:5", false, {}},
    {"GulA", "dgul-HEX|6:a", "1:5", false, {}},
    {"AltA", "lalt-HEX|6:a", "1:5", false, {}},
    {"AllA", "dall-HEX|6:a", "1:5", false, {}},
    {"TalA", "dtal-HEX|6:a", "1:5", false, {}},
    {"IdoA", "lido-HEX|6:a", "1:5", false, {}},
    {"Fuc", "lgal-HEX|6:d", "1:5", false, {}},
    {"Fuc", "lxyl-HEX|4:d|6:d", "1:5", false, {}},
    {"Qui", "dglc-HEX|6:d", "1:5", false, {}},
    {"Rha", "lman-HEX|6:d", "1:5", false, {}},
    {"6dGul", "dgul-HEX|6:d", "1:5", false, {}},
    {"6dAlt", "lalt-HEX|6:d", "1:5", false, {}},
    {"6dTal", "dtal-HEX|6:d", "1:5", false, {}},
    {"FucNAc", "lgal-HEX|6:d", "1:5", false, {"n-acetyl\r2\r1"}},
    {"QuiNAc", "dglc-HEX|6:d", "1:5", false, {"n-acetyl\r2\r1"}},
    {"RhaNAc", "lman-HEX|6:d", "1:5", false, {"n-acetyl\r2\r1"}},
    {"6dAltNAc", "lalt-HEX|6:d", "1:5", false, {"n-acetyl\r2\r1"}},
    {"6dTalNAc", "dtal-HEX|6:d", "1:5", false, {"n-acetyl\r2\r1"}},
    {"Oli", "dara-HEX|2:d|6:d", "1:5", false, {}},
    {"Tyv", "dara-HEX|3:d|6:d", "1:5", false, {}},
    {"Abe", "dxyl-HEX|3:d|6:d", "1:5", false, {}},
    {"Par", "drib-HEX|3:d|6:d", "1:5", false, {}},
    {"Dig", "drib-HEX|2:d|6:d", "1:5", false, {}},
    {"Col", "lxyl-HEX|3:d|6:d", "1:5", false, {}},
    {"Ara", "lara-PEN", "1:5", false, {}},
    {"Lyx", "llyx-PEN", "1:5", false, {}},
    {"Xyl", "dxyl-PEN", "1:5", false, {}},
    {"Rib", "drib-PEN", "1:5", false, {}},
    {"Kdn", "dgro-dgal-NON|1:a|2:keto|3:d", "2:6", false, {}},
    {"Neu", "dgro-dgal-NON|1:a|2:keto|3:d", "2:6", false, {"amino\r5\r1"}},
    {"Neu5Ac", "dgro-dgal-NON|1:a|2:keto|3:d", "2:6", false, {"n-acetyl\r5\r1"}},
    {"Neu5Gc", "dgro-dgal-NON|1:a|2:keto|3:d", "2:6", false, {"n-glycolyl\r5\r1"}},
    {"Pse",
     "lgro-lman-NON|2:keto|3:d|9:d",
     "2:6",
     false,
     {"amino\r5\r1", "amino\r7\r1"}},
    {"Leg",
     "dgro-dgal-NON|1:a|2:keto|3:d|9:d",
     "2:6",
     false,
     {"amino\r5\r1", "amino\r7\r1"}},
    {"Aci",
     "lgro-lalt-NON|1:a|2:keto|3:d|9:d",
     "2:6",
     false,
     {"amino\r5\r1", "amino\r7\r1"}},
    {"4eLeg",
     "dgro-dtal-NON|1:a|2:keto|3:d|9:d",
     "2:6",
     false,
     {"amino\r5\r1", "amino\r7\r1"}},
    {"Bac", "dglc-HEX|6:d", "1:5", false, {"amino\r2\r1", "amino\r4\r1"}},
    {"LDmanHep", "lgro-dman-HEP", "1:5", false, {}},
    {"Kdo", "dman-OCT|1:a|2:keto|3:d", "2:6", false, {}},
    {"Dha", "dlyx-HEP|1:a|2:keto|3:d|7:a", "2:6", false, {}},
    {"DDmanHep", "dgro-dman-HEP", "1:5", false, {}},
    {"MurNAc", "dglc-HEX", "1:5", false, {"(r)-carboxyethyl\r3\r1", "n-acetyl\r2\r1"}},
    {"MurNGc",
     "dglc-HEX",
     "1:5",
     false,
     {"(r)-carboxyethyl\r3\r1", "n-glycolyl\r2\r1"}},
    {"Mur", "dglc-HEX", "1:5", false, {"(r)-carboxyethyl\r3\r1"}},
    {"Fru", "dara-HEX|2:keto", "2:6", false, {}},
    {"Tag", "dlyx-HEX|2:keto", "2:6", false, {}},
    {"Sor", "lxyl-HEX|2:keto", "2:6", false, {}},
    {"Psi", "drib-HEX|2:keto", "2:6", false, {}},
    {"L-Glc", "lglc-HEX", "1:5", false, {}},
    {"L-Man", "lman-HEX", "1:5", false, {}},
    {"L-Gal", "lgal-HEX", "1:5", false, {}},
    {"L-Gul", "lgul-HEX", "1:5", false, {}},
    {"D-Alt", "dalt-HEX", "1:5", false, {}},
    {"L-All", "lall-HEX", "1:5", false, {}},
    {"L-Tal", "ltal-HEX", "1:5", false, {}},
    {"D-Ido", "dido-HEX", "1:5", false, {}},
    {"L-GlcNAc", "lglc-HEX", "1:5", false, {"n-acetyl\r2\r1"}},
    {"L-GalNAc", "lgal-HEX", "1:5", false, {"n-acetyl\r2\r1"}},
    {"L-ManNAc", "lman-HEX", "1:5", false, {"n-acetyl\r2\r1"}},
    {"L-GulNAc", "lgul-HEX", "1:5", false, {"n-acetyl\r2\r1"}},
    {"D-AltNAc", "dalt-HEX", "1:5", false, {"n-acetyl\r2\r1"}},
    {"L-AllNAc", "lall-HEX", "1:5", false, {"n-acetyl\r2\r1"}},
    {"L-TalNAc", "ltal-HEX", "1:5", false, {"n-acetyl\r2\r1"}},
    {"D-IdoNAc", "dido-HEX", "1:5", false, {"n-acetyl\r2\r1"}},
    {"L-GlcN", "lglc-HEX", "1:5", false, {"amino\r2\r1"}},
    {"L-ManN", "lman-HEX", "1:5", false, {"amino\r2\r1"}},
    {"L-GalN", "lgal-HEX", "1:5", false, {"amino\r2\r1"}},
    {"L-GulN", "lgul-HEX", "1:5", false, {"amino\r2\r1"}},
    {"D-AltN", "dalt-HEX", "1:5", false, {"amino\r2\r1"}},
    {"L-AllN", "lall-HEX", "1:5", false, {"amino\r2\r1"}},
    {"L-TalN", "ltal-HEX", "1:5", false, {"amino\r2\r1"}},
    {"D-IdoN", "dido-HEX", "1:5", false, {"amino\r2\r1"}},
    {"L-GlcA", "lglc-HEX|6:a", "1:5", false, {}},
    {"L-ManA", "lman-HEX|6:a", "1:5", false, {}},
    {"L-GalA", "lgal-HEX|6:a", "1:5", false, {}},
    {"L-GulA", "lgul-HEX|6:a", "1:5", false, {}},
    {"D-AltA", "dalt-HEX|6:a", "1:5", false, {}},
    {"L-AllA", "lall-HEX|6:a", "1:5", false, {}},
    {"L-TalA", "ltal-HEX|6:a", "1:5", false, {}},
    {"D-IdoA", "dido-HEX|6:a", "1:5", false, {}},
    {"D-Fuc", "dgal-HEX|6:d", "1:5", false, {}},
    {"D-Fuc", "dxyl-HEX|4:d|6:d", "1:5", false, {}},
    {"L-Qui", "lglc-HEX|6:d", "1:5", false, {}},
    {"D-Rha", "dman-HEX|6:d", "1:5", false, {}},
    {"L-6dGul", "lgul-HEX|6:d", "1:5", false, {}},
    {"D-6dAlt", "dalt-HEX|6:d", "1:5", false, {}},
    {"L-6dTal", "ltal-HEX|6:d", "1:5", false, {}},
    {"D-FucNAc", "dgal-HEX|6:d", "1:5", false, {"n-acetyl\r2\r1"}},
    {"L-QuiNAc", "lglc-HEX|6:d", "1:5", false, {"n-acetyl\r2\r1"}},
    {"D-RhaNAc", "dman-HEX|6:d", "1:5", false, {"n-acetyl\r2\r1"}},
    {"D-6dAltNAc", "dalt-HEX|6:d", "1:5", false, {"n-acetyl\r2\r1"}},
    {"L-6dTalNAc", "ltal-HEX|6:d", "1:5", false, {"n-acetyl\r2\r1"}},
    {"L-Oli", "lara-HEX|2:d|6:d", "1:5", false, {}},
    {"L-Tyv", "lara-HEX|3:d|6:d", "1:5", false, {}},
    {"L-Par", "lrib-HEX|3:d|6:d", "1:5", false, {}},
    {"L-Dig", "lrib-HEX|2:d|6:d", "1:5", false, {}},
    {"D-Ara", "dara-PEN", "1:5", false, {}},
    {"L-Lyx", "dlyx-PEN", "1:5", false, {}},
    {"L-Xyl", "lxyl-PEN", "1:5", false, {}},
    {"L-Rib", "lrib-PEN", "1:5", false, {}},
    {"L-Kdn", "lgro-lgal-NON|1:a|2:keto|3:d", "2:6", false, {}},
    {"L-Neu5Ac", "lgro-lgal-NON|1:a|2:keto|3:d", "2:6", false, {"n-acetyl\r5\r1"}},
    {"L-Neu5Gc", "lgro-lgal-NON|1:a|2:keto|3:d", "2:6", false, {"n-glycolyl\r5\r1"}},
    {"L-Bac", "lglc-HEX|6:d", "1:5", false, {"amino\r2\r1", "amino\r4\r1"}},
    {"L-Kdo", "lman-OCT|1:a|2:keto|3:d", "2:6", false, {}},
    {"L-Dha", "llyx-HEP|1:a|2:keto|3:d|7:a", "2:6", false, {}},
    {"L-MurNAc",
     "lglc-HEX",
     "1:5",
     false,
     {"(r)-carboxyethyl\r3\r1", "n-acetyl\r2\r1"}},
    {"L-MurNGc",
     "lglc-HEX",
     "1:5",
     false,
     {"(r)-carboxyethyl\r3\r1", "n-glycolyl\r2\r1"}},
    {"L-Mur", "lglc-HEX", "1:5", false, {"(r)-carboxyethyl\r3\r1"}},
    {"L-Fru", "lara-HEX|2:keto", "2:6", false, {}},
    {"L-Tag", "llyx-HEX|2:keto", "2:6", false, {}},
    {"D-Sor", "dxyl-HEX|2:keto", "2:6", false, {}},
    {"L-Psi", "lrib-HEX|2:keto", "2:6", false, {}}};
inline const std::vector<CTMapping> glycoct_alditol_entries = {
    {"Glc", "dglc-HEX|1:aldi", "0:0", true, {}},
    {"Man", "dman-HEX|1:aldi", "0:0", true, {}},
    {"Gal", "dgal-HEX|1:aldi", "0:0", true, {}},
    {"Gul", "dgul-HEX|1:aldi", "0:0", true, {}},
    {"Alt", "ltal-HEX|1:aldi", "0:0", true, {}},
    {"All", "dall-HEX|1:aldi", "0:0", true, {}},
    {"Tal", "dalt-HEX|1:aldi", "0:0", true, {}},
    {"Ido", "lido-HEX|1:aldi", "0:0", true, {}},
    {"GlcNAc", "dglc-HEX|1:aldi", "0:0", true, {"n-acetyl\r2\r1"}},
    {"GalNAc", "dgal-HEX|1:aldi", "0:0", true, {"n-acetyl\r2\r1"}},
    {"ManNAc", "dman-HEX|1:aldi", "0:0", true, {"n-acetyl\r2\r1"}},
    {"GulNAc", "dgul-HEX|1:aldi", "0:0", true, {"n-acetyl\r2\r1"}},
    {"AltNAc", "ltal-HEX|1:aldi", "0:0", true, {"n-acetyl\r5\r1"}},
    {"AllNAc", "dall-HEX|1:aldi", "0:0", true, {"n-acetyl\r2\r1"}},
    {"TalNAc", "dalt-HEX|1:aldi", "0:0", true, {"n-acetyl\r5\r1"}},
    {"IdoNAc", "lido-HEX|1:aldi", "0:0", true, {"n-acetyl\r2\r1"}},
    {"GlcN", "dglc-HEX|1:aldi", "0:0", true, {"amino\r2\r1"}},
    {"ManN", "dman-HEX|1:aldi", "0:0", true, {"amino\r2\r1"}},
    {"GalN", "dgal-HEX|1:aldi", "0:0", true, {"amino\r2\r1"}},
    {"GulN", "dgul-HEX|1:aldi", "0:0", true, {"amino\r2\r1"}},
    {"AltN", "ltal-HEX|1:aldi", "0:0", true, {"amino\r5\r1"}},
    {"AllN", "dall-HEX|1:aldi", "0:0", true, {"amino\r2\r1"}},
    {"TalN", "dalt-HEX|1:aldi", "0:0", true, {"amino\r5\r1"}},
    {"IdoN", "lido-HEX|1:aldi", "0:0", true, {"amino\r2\r1"}},
    {"Fuc", "lgal-HEX|1:aldi|6:d", "0:0", true, {}},
    {"Qui", "dglc-HEX|1:aldi|6:d", "0:0", true, {}},
    {"Rha", "lman-HEX|1:aldi|6:d", "0:0", true, {}},
    {"6dGul", "dgul-HEX|1:aldi|6:d", "0:0", true, {}},
    {"6dAlt", "lalt-HEX|1:aldi|6:d", "0:0", true, {}},
    {"6dTal", "dtal-HEX|1:aldi|6:d", "0:0", true, {}},
    {"FucNAc", "lgal-HEX|1:aldi|6:d", "0:0", true, {"n-acetyl\r2\r1"}},
    {"QuiNAc", "dglc-HEX|1:aldi|6:d", "0:0", true, {"n-acetyl\r2\r1"}},
    {"RhaNAc", "lman-HEX|1:aldi|6:d", "0:0", true, {"n-acetyl\r2\r1"}},
    {"6dAltNAc", "lalt-HEX|1:aldi|6:d", "0:0", true, {"n-acetyl\r2\r1"}},
    {"6dTalNAc", "dtal-HEX|1:aldi|6:d", "0:0", true, {"n-acetyl\r2\r1"}},
    {"Oli", "dara-HEX|1:aldi|2:d|6:d", "0:0", true, {}},
    {"Tyv", "dara-HEX|1:aldi|3:d|6:d", "0:0", true, {}},
    {"Abe", "dxyl-HEX|1:aldi|3:d|6:d", "0:0", true, {}},
    {"Par", "drib-HEX|1:aldi|3:d|6:d", "0:0", true, {}},
    {"Dig", "drib-HEX|1:aldi|2:d|6:d", "0:0", true, {}},
    {"Col", "lxyl-HEX|1:aldi|3:d|6:d", "0:0", true, {}},
    {"Lyx", "llyx-PEN|1:aldi", "0:0", true, {}},
    {"Xyl", "dxyl-PEN|1:aldi", "0:0", true, {}},
    {"Rib", "drib-PEN|1:aldi", "0:0", true, {}},
    {"Bac", "dglc-HEX|1:aldi|6:d", "0:0", true, {"amino\r2\r1", "amino\r4\r1"}},
    {"LDmanHep", "dgro-dgal-HEP|1:aldi", "0:0", true, {}},
    {"DDmanHep", "dgro-dman-HEP|1:aldi", "0:0", true, {}},
    {"MurNAc",
     "dglc-HEX|1:aldi",
     "0:0",
     true,
     {"(r)-carboxyethyl\r3\r1", "n-acetyl\r2\r1"}},
    {"MurNGc",
     "dglc-HEX|1:aldi",
     "0:0",
     true,
     {"(r)-carboxyethyl\r3\r1", "n-glycolyl\r2\r1"}},
    {"Mur", "dglc-HEX|1:aldi", "0:0", true, {"(r)-carboxyethyl\r3\r1"}},
    {"L-Glc", "lglc-HEX|1:aldi", "0:0", true, {}},
    {"L-Man", "lman-HEX|1:aldi", "0:0", true, {}},
    {"L-Gal", "lgal-HEX|1:aldi", "0:0", true, {}},
    {"L-Gul", "lgul-HEX|1:aldi", "0:0", true, {}},
    {"D-Alt", "dtal-HEX|1:aldi", "0:0", true, {}},
    {"L-All", "lall-HEX|1:aldi", "0:0", true, {}},
    {"L-Tal", "lalt-HEX|1:aldi", "0:0", true, {}},
    {"D-Ido", "dido-HEX|1:aldi", "0:0", true, {}},
    {"L-GlcNAc", "lglc-HEX|1:aldi", "0:0", true, {"n-acetyl\r2\r1"}},
    {"L-GalNAc", "lgal-HEX|1:aldi", "0:0", true, {"n-acetyl\r2\r1"}},
    {"L-ManNAc", "lman-HEX|1:aldi", "0:0", true, {"n-acetyl\r2\r1"}},
    {"L-GulNAc", "lgul-HEX|1:aldi", "0:0", true, {"n-acetyl\r2\r1"}},
    {"D-AltNAc", "dtal-HEX|1:aldi", "0:0", true, {"n-acetyl\r5\r1"}},
    {"L-AllNAc", "lall-HEX|1:aldi", "0:0", true, {"n-acetyl\r2\r1"}},
    {"L-TalNAc", "lalt-HEX|1:aldi", "0:0", true, {"n-acetyl\r5\r1"}},
    {"D-IdoNAc", "dido-HEX|1:aldi", "0:0", true, {"n-acetyl\r2\r1"}},
    {"L-GlcN", "lglc-HEX|1:aldi", "0:0", true, {"amino\r2\r1"}},
    {"L-ManN", "lman-HEX|1:aldi", "0:0", true, {"amino\r2\r1"}},
    {"L-GalN", "lgal-HEX|1:aldi", "0:0", true, {"amino\r2\r1"}},
    {"L-GulN", "lgul-HEX|1:aldi", "0:0", true, {"amino\r2\r1"}},
    {"D-AltN", "dtal-HEX|1:aldi", "0:0", true, {"amino\r5\r1"}},
    {"L-AllN", "lall-HEX|1:aldi", "0:0", true, {"amino\r2\r1"}},
    {"L-TalN", "lalt-HEX|1:aldi", "0:0", true, {"amino\r5\r1"}},
    {"D-IdoN", "dido-HEX|1:aldi", "0:0", true, {"amino\r2\r1"}},
    {"D-Fuc", "dgal-HEX|1:aldi|6:d", "0:0", true, {}},
    {"L-Qui", "lglc-HEX|1:aldi|6:d", "0:0", true, {}},
    {"D-Rha", "dman-HEX|1:aldi|6:d", "0:0", true, {}},
    {"L-6dGul", "lgul-HEX|1:aldi|6:d", "0:0", true, {}},
    {"D-6dAlt", "dalt-HEX|1:aldi|6:d", "0:0", true, {}},
    {"L-6dTal", "ltal-HEX|1:aldi|6:d", "0:0", true, {}},
    {"D-FucNAc", "dgal-HEX|1:aldi|6:d", "0:0", true, {"n-acetyl\r2\r1"}},
    {"L-QuiNAc", "lglc-HEX|1:aldi|6:d", "0:0", true, {"n-acetyl\r2\r1"}},
    {"D-RhaNAc", "dman-HEX|1:aldi|6:d", "0:0", true, {"n-acetyl\r2\r1"}},
    {"D-6dAltNAc", "dalt-HEX|1:aldi|6:d", "0:0", true, {"n-acetyl\r2\r1"}},
    {"L-6dTalNAc", "ltal-HEX|1:aldi|6:d", "0:0", true, {"n-acetyl\r2\r1"}},
    {"L-Oli", "lara-HEX|1:aldi|2:d|6:d", "0:0", true, {}},
    {"L-Tyv", "lara-HEX|1:aldi|3:d|6:d", "0:0", true, {}},
    {"L-Par", "lrib-HEX|1:aldi|3:d|6:d", "0:0", true, {}},
    {"L-Dig", "lrib-HEX|1:aldi|2:d|6:d", "0:0", true, {}},
    {"L-Lyx", "dlyx-PEN|1:aldi", "0:0", true, {}},
    {"L-Xyl", "lxyl-PEN|1:aldi", "0:0", true, {}},
    {"L-Rib", "lrib-PEN|1:aldi", "0:0", true, {}},
    {"L-Bac", "lglc-HEX|1:aldi|6:d", "0:0", true, {"amino\r2\r1", "amino\r4\r1"}},
    {"L-MurNAc",
     "lglc-HEX|1:aldi",
     "0:0",
     true,
     {"(r)-carboxyethyl\r3\r1", "n-acetyl\r2\r1"}},
    {"L-MurNGc",
     "lglc-HEX|1:aldi",
     "0:0",
     true,
     {"(r)-carboxyethyl\r3\r1", "n-glycolyl\r2\r1"}},
    {"L-Mur", "lglc-HEX|1:aldi", "0:0", true, {"(r)-carboxyethyl\r3\r1"}}};
} // namespace gp
#endif
