// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// native_convert_cpp
Rcpp::CharacterVector native_convert_cpp(Rcpp::CharacterVector x, const std::string& format, Rcpp::List vocabulary);
RcppExport SEXP _glyparse_native_convert_cpp(SEXP xSEXP, SEXP formatSEXP, SEXP vocabularySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type format(formatSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type vocabulary(vocabularySEXP);
    rcpp_result_gen = Rcpp::wrap(native_convert_cpp(x, format, vocabulary));
    return rcpp_result_gen;
END_RCPP
}
// native_records_cpp
Rcpp::List native_records_cpp(Rcpp::CharacterVector x, const std::string& format, Rcpp::List vocabulary);
RcppExport SEXP _glyparse_native_records_cpp(SEXP xSEXP, SEXP formatSEXP, SEXP vocabularySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type format(formatSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type vocabulary(vocabularySEXP);
    rcpp_result_gen = Rcpp::wrap(native_records_cpp(x, format, vocabulary));
    return rcpp_result_gen;
END_RCPP
}
// native_aux_cpp
Rcpp::RObject native_aux_cpp(const std::string& op, Rcpp::List args, Rcpp::List vocabulary);
RcppExport SEXP _glyparse_native_aux_cpp(SEXP opSEXP, SEXP argsSEXP, SEXP vocabularySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type op(opSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type vocabulary(vocabularySEXP);
    rcpp_result_gen = Rcpp::wrap(native_aux_cpp(op, args, vocabulary));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_glyparse_native_convert_cpp", (DL_FUNC) &_glyparse_native_convert_cpp, 3},
    {"_glyparse_native_records_cpp", (DL_FUNC) &_glyparse_native_records_cpp, 3},
    {"_glyparse_native_aux_cpp", (DL_FUNC) &_glyparse_native_aux_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_glyparse(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
