# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

native_convert_cpp <- function(x, format, vocabulary) {
    .Call(`_glyparse_native_convert_cpp`, x, format, vocabulary)
}

native_records_cpp <- function(x, format, vocabulary) {
    .Call(`_glyparse_native_records_cpp`, x, format, vocabulary)
}

native_aux_cpp <- function(op, args, vocabulary) {
    .Call(`_glyparse_native_aux_cpp`, op, args, vocabulary)
}

